<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;

class OptionsSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		if (App::environment(['production'])) {
			print "\nOpps! you are in production environment. You are not authorized to run.\n";
			die();
		}

		DB::table('options')->truncate();

		$options = array(
			array('field_type' => 'text', 'field_label' => NULL, 'option_key' => 'sbscp_status', 'option_value' => '2', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'subscription', 'field_info' => '', 'is_required' => 'n', 'c_order' => '0', 'status' => '1', 'updated_id' => '0', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => NULL, 'option_key' => 'sbscp_end_date', 'option_value' => '13-02-2019', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'subscription', 'field_info' => '', 'is_required' => 'n', 'c_order' => '0', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Title', 'option_key' => 'title', 'option_value' => 'myplexus.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'general', 'field_info' => '', 'is_required' => 'y', 'c_order' => '1', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'image', 'field_label' => 'Logo', 'option_key' => 'logo', 'option_value' => 'myplexus-LOGO.png', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'general', 'field_info' => 'Only JPEG and PNG image allowed.<br/>For best view image size should be in W=---px, H=---px and under 250KB.', 'is_required' => 'y', 'c_order' => '2', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'image', 'field_label' => 'Email Template Logo', 'option_key' => 'email_template_logo', 'option_value' => 'myplexus-Email-LOGO.png', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'general', 'field_info' => 'Only JPEG and PNG image allowed.<br/>For best view image size should be in W=---px, H=--px and under 250KB.', 'is_required' => 'n', 'c_order' => '3', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'From Email Address', 'option_key' => 'from_email', 'option_value' => 'auth@lageraho.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'general', 'field_info' => 'This email is used for app from email communication.', 'is_required' => 'y', 'c_order' => '5', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'To Email Address', 'option_key' => 'to_email', 'option_value' => 'vikash@showtimemedia.in', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'general', 'field_info' => 'This email is used for app to email communication.', 'is_required' => 'y', 'c_order' => '6', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'dropdown', 'field_label' => 'Mail Protocol', 'option_key' => 'mail_protocol', 'option_value' => '2', 'options_label' => '["SMTP"]', 'options_value' => '[2]', 'type' => 'mail_setting', 'field_info' => '', 'is_required' => 'y', 'c_order' => '1', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'dropdown', 'field_label' => 'SMTP Secure', 'option_key' => 'smtp_secure', 'option_value' => '', 'options_label' => '["TLS", "SSL"]', 'options_value' => '["tls", "ssl"]', 'type' => 'mail_setting', 'field_info' => 'If you\'re using secure domain choose SSL, If not then use TLS. <br/>Secure transfer enabled REQUIRED for Gmail<br/>If No secure type then leave as blank', 'is_required' => 'n', 'c_order' => '2', 'status' => '2', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'SMTP Hostname', 'option_key' => 'smtp_hostname', 'option_value' => 'mail.lageraho.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'mail_setting', 'field_info' => 'Hostname of the mail server. <br/>If Email run from server then use Domain name like "konzern.co.in" and if Email run from Gmail then use "smtp.gmail.com"', 'is_required' => 'y', 'c_order' => '3', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'SMTP Port', 'option_key' => 'smtp_port', 'option_value' => '25', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'mail_setting', 'field_info' => 'Port of the SMTP like to be 25, 80, 465 or 587. <br/>If Email run from server then use 25 or 80 and if Email run from Gmail then use 465 or 587', 'is_required' => 'y', 'c_order' => '4', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'SMTP Username', 'option_key' => 'smtp_username', 'option_value' => 'auth@lageraho.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'mail_setting', 'field_info' => 'Username for SMTP authentication any valid email created in your domain', 'is_required' => 'y', 'c_order' => '5', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'SMTP Password', 'option_key' => 'smtp_password', 'option_value' => 'Csvu6#48', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'mail_setting', 'field_info' => 'Password for SMTP authentication(Password of above email)', 'is_required' => 'y', 'c_order' => '6', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Facebook', 'option_key' => 'facebook', 'option_value' => 'https://www.facebook.com/MyplexusMF', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'social', 'field_info' => 'Put valid url with http:// or https://', 'is_required' => 'n', 'c_order' => '1', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Twitter', 'option_key' => 'twitter', 'option_value' => 'https://twitter.com/myplexusMF', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'social', 'field_info' => 'Put valid url with http:// or https://', 'is_required' => 'n', 'c_order' => '2', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'LinkedIn', 'option_key' => 'linkedin', 'option_value' => 'https://www.linkedin.com/company/myplexus.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'social', 'field_info' => 'Put valid url with http:// or https://', 'is_required' => 'n', 'c_order' => '3', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'image', 'field_label' => 'Footer Logo', 'option_key' => 'footer_logo', 'option_value' => 'myplexus-footer-logo.png', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'Only JPEG and PNG image allowed.<br/>For best view image size should be in W=125px, H=70px and under 250KB.', 'is_required' => 'n', 'c_order' => '1', 'status' => '2', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Quick Link 1 Label', 'option_key' => 'quick_link_1', 'option_value' => 'Quick Links', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'For website footer.', 'is_required' => 'n', 'c_order' => '2', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Quick Link 2 Label', 'option_key' => 'quick_link_2', 'option_value' => 'Navigation', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'For website footer.', 'is_required' => 'n', 'c_order' => '3', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Quick Contact Label', 'option_key' => 'quick_contact_label', 'option_value' => 'Contact Us', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'For website footer.', 'is_required' => 'n', 'c_order' => '4', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'textarea', 'field_label' => 'Address', 'option_key' => 'address', 'option_value' => '11/5, 75C Park Street.Kolkata-700016.', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'n', 'c_order' => '5', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Contact 1', 'option_key' => 'contact1', 'option_value' => '09073977460', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'n', 'c_order' => '6', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Contact 2', 'option_key' => 'contact2', 'option_value' => '03340646145', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'n', 'c_order' => '8', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),

			array('field_type' => 'text', 'field_label' => 'AUM Last Saved', 'option_key' => 'aum', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 16:38:58'),
			array('field_type' => 'text', 'field_label' => 'AUM Last Publish', 'option_key' => 'aum_publish', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-21 13:24:36'),
			array('field_type' => 'text', 'field_label' => 'Currency Last Saved', 'option_key' => 'cur', 'option_value' => '2021-12-10', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-21 12:39:57'),
			array('field_type' => 'text', 'field_label' => 'Currency Last Publish', 'option_key' => 'cur_publish', 'option_value' => '2021-12-10', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-21 12:58:53'),
			array('field_type' => 'text', 'field_label' => 'Fund Composition Last Saved', 'option_key' => 'fund_comp', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 15:21:47'),
			array('field_type' => 'text', 'field_label' => 'Fund Composition Last Publish', 'option_key' => 'fund_comp_publish', 'option_value' => '2021-12-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 11:44:06'),
			array('field_type' => 'text', 'field_label' => 'Indices Last Saved', 'option_key' => 'idx', 'option_value' => '2022-01-18', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-18 17:57:39'),
			array('field_type' => 'text', 'field_label' => 'Indices Last Publish', 'option_key' => 'idx_publish', 'option_value' => '2022-01-18', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-21 12:16:30'),
			array('field_type' => 'text', 'field_label' => 'Indices Composition Last Saved', 'option_key' => 'idx_comp', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 16:43:26'),
			array('field_type' => 'text', 'field_label' => 'Indices Composition Last Publish', 'option_key' => 'idx_comp_publish', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-21 13:53:58'),
			array('field_type' => 'text', 'field_label' => 'MCAP EPS Last Saved', 'option_key' => 'mcap', 'option_value' => '2022-01-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 16:36:07'),
			array('field_type' => 'text', 'field_label' => 'MCAP EPS Last Publish', 'option_key' => 'mcap_publish', 'option_value' => '2021-12-31', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-28 16:28:51'),
			array('field_type' => 'text', 'field_label' => 'NAV Last Saved', 'option_key' => 'nav', 'option_value' => '2022-01-07', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-20 16:27:16'),
			array('field_type' => 'text', 'field_label' => 'NAV Last Publish', 'option_key' => 'nav_publish', 'option_value' => '2022-01-07', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'y', 'c_order' => '0', 'status' => '2', 'updated_id' => '1', 'updated_at' => '2022-01-20 20:33:21'),

			array('field_type' => 'text', 'field_label' => 'Contact 1 Text', 'option_key' => 'contact1_txt', 'option_value' => 'INDIA- 09073977460', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'n', 'c_order' => '7', 'status' => '2', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Contact 2 Text', 'option_key' => 'contact2_txt', 'option_value' => 'INDIA- 033-40646145', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => '', 'is_required' => 'n', 'c_order' => '9', 'status' => '2', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Welcome Text', 'option_key' => 'welcome_txt', 'option_value' => 'Welcome To myplexus.com', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'For website header.', 'is_required' => 'n', 'c_order' => '10', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),

			array('field_type' => 'text', 'field_label' => 'Paathshaala Heading', 'option_key' => 'paathshaala_heading', 'option_value' => 'MyPlexus Paathshaala', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'Used for website home and FAQ pages.', 'is_required' => 'n', 'c_order' => '11', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'image', 'field_label' => 'Paathshaala Image', 'option_key' => 'paathshaala_image', 'option_value' => '', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'Only JPEG and PNG image allowed.<br>For best view image size should be in W=325px, H=259px and under 250KB.<br>Used for website home and FAQ pages.', 'is_required' => 'n', 'c_order' => '12', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'text', 'field_label' => 'Newsletter Heading', 'option_key' => 'newsletter_heading', 'option_value' => 'Newsletter Signup', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'Used for website home and FAQ pages.', 'is_required' => 'n', 'c_order' => '13', 'status' => '1', 'updated_id' => '1', 'updated_at' => now()),
			array('field_type' => 'textarea', 'field_label' => 'Newsletter Description', 'option_key' => 'newsletter_description', 'option_value' => 'An unique layout that very simply outlines various performance parameters, in numerical and colour coded styles that help you in understanding how funds have performed Your first...', 'options_label' => NULL, 'options_value' => NULL, 'type' => 'custom', 'field_info' => 'Used for website home and FAQ pages.', 'is_required' => 'n', 'c_order' => '14', 'status' => '1', 'updated_id' => '1', 'updated_at' => now())
		);

		DB::table('options')->insert($options);
		$this->command->info('Options table seeded!');
	}
}
