services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: myproj
    container_name: myproj-app
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=2000
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
      APP_URL: http://127.0.0.1:2000
    ports:
      - "2000:2000"
    volumes:
      - ./:/var/www
      - ./.env.docker:/var/www/.env
    networks:
      - myproj
    
networks:
  myproj:
    driver: bridge
