@extends('web.layout.app')
@section('content')
<section class="inner_banner_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="inner_section_banner">
                    <h4>Penta Tech</h4>
                    <p>The mutual fund industry is fast becoming the preferred savings and investment vehicle for most of us.</p>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="pentatech_section section">
    <div class="container">
        <div class="row">
            <div class="co-md-12">
                <div class="pentatech_inner_wrapper">
                    <div class="pentatech_inner">
                        <div class="pentatech_filter_title">
                            <h4>PentaTec Filter</h4>
                        </div>
                        <div class="pentactech_desc">
                            <p>A system designed by us a myplexus.com to identify winners A sequence of filters is employed by us to reduce the fund manager's performance to quantifiable terms. The intention is to identify the quality of performance and ascertain the manager's capability to repeat the performance. Never once do the returns generated by the fund figure in the chosen parameters that we employ to ascertain management competence. Returns are the result of doing myriad activities right. Essentially it involves an exercise to figure out the DNA of the fund managers investment skills. So it makes sense to distill the characteristics of the manager over a defined time period and analyse the DNA to reach a conclusion.</p>
                            <p>The rigourous process of eliminating "chance" leads to higher predictive quality. As the process involved is completely quantitative, it eliminates bias and imparts clarity.</p>
                        </div>

                        <div class="row mt-5">
                            <div class="col-md-8 offset-md-2">
                                <div class="pentatech_filter">
                                    <div class="single_pentatect_item_wrapper trans1">
                                        <div class="single_pentatect_item light_bg_filter funnel1">
                                            <h4>Scheme Category Population</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans2">
                                        <div class="single_pentatect_item dark_bg_filter funnel2">
                                            <h4>Return Ratio Filter (Wt.60%) <br>Risk Ratio Filter (Wt.>40%)</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans3">
                                        <div class="single_pentatect_item yellow_bg_filter funnel3">
                                            <h4>Filtered Scheme</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans4">
                                        <div class="single_pentatect_item dark_bg_filter funnel4">
                                            <h4>Contra Isolator</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans5">
                                        <div class="single_pentatect_item yellow_bg_filter funnel5">
                                            <h4>Filtered Scheme</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans6">
                                        <div class="single_pentatect_item dark_bg_filter funnel6">
                                            <h4>SKEW AND PEAK FILTER</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans7">
                                        <div class="single_pentatect_item yellow_bg_filter funnel7">
                                            <h4>Filtered Scheme</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans8">
                                        <div class="single_pentatect_item dark_bg_filter funnel8">
                                            <h4>COMPOSITION SYMMETRY</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans9">
                                        <div class="single_pentatect_item yellow_bg_filter funnel9">
                                            <h4>SELECTED SCHEMES</h4>
                                        </div>
                                    </div>
                                    <div class="single_pentatect_item_wrapper trans10">
                                        <div class="single_pentatect_item yellow_bg_filter funnel10">
                                            <h4>SELECTED SCHEMES</h4>
                                        </div>
                                    </div>
                                    <div class="finel_img text-center">
                                    <img src="{{asset('themes/frontend/assets/v1/img/funel_img.png')}}" class="funel_img"/>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@stop
@push('style')
@endpush