USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpMonthlyIndices]    Script Date: 02-03-2022 10:55:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER      PROCEDURE [dbo].[SpMonthlyIndices]

@EntryDate		VARCHAR(10),
@TypeID		INT
-- @TermID		INT


AS

BEGIN

SET NOCOUNT ON;

		SELECT Z.INDICESNAME, Z.AVG6, Z.AVG1, Z.AVG2, Z.AVG3 FROM

		(SELECT X.INDICESNAME, 
		"AVG6" 
		      = CASE 
		        WHEN X.STARTING6 <> 0 THEN ((X.CLOSING6 - X.STARTING6) / X.STARTING6) * 100
		        WHEN X.STARTING6 = 0 THEN 0
		        END,
		
		"AVG1" 
		      = CASE 
		        WHEN X.STARTING1 <> 0 THEN ((X.CLOSING1 - X.STARTING1) / X.STARTING1) * 100
		        WHEN X.STARTING1 = 0 THEN 0
		        END,		
		"AVG2" 
		      = CASE 
		        WHEN X.STARTING2 <> 0 THEN ((POWER((X.CLOSING2/X.STARTING2),0.5) -1) * 100)
		        WHEN X.STARTING2 = 0 THEN 0
		        END,
		
		"AVG3" 
		      = CASE 
		        WHEN X.STARTING3 <> 0 THEN ((POWER((X.CLOSING3/X.STARTING3),0.33) -1) * 100)
		        WHEN X.STARTING3 = 0 THEN 0
		        END
		
		FROM
		   
		 (SELECT Y.INDICESNAME, 
		  
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING6,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING6,
		   
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING1,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING1,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING2,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING2,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND 

		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING3,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING3
		

		   FROM (SELECT DISTINCT TBINDICESDETAIL.INDICESNAME, MIN(TBINDICESDETAIL.ENTRYDATE) AS OPDATE FROM TBINDICESDETAIL INNER JOIN 
				TBFUNDMASTER ON TBINDICESDETAIL.INDICESNAME = TBFUNDMASTER.INDICESNAME
				WHERE TBINDICESDETAIL.ENTRYDATE < CONVERT(DATETIME, @EntryDate, 103) 
			--	AND TBFUNDMASTER.FUNDTERMID = @TermID
				AND TBFUNDMASTER.FUNDTYPEID = @TypeID GROUP BY TBINDICESDETAIL.INDICESNAME) Y) X)Z
		 ORDER BY Z.AVG6 DESC

END
