USE [MYPLEXUSDB_70803]
GO
    /****** Object:  StoredProcedure [dbo].[SpPerformanceRankingIndividual]    Script Date: 02-03-2022 18:30:03 ******/
SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    ALTER PROCEDURE [dbo].[SpPerformanceRankingIndividual] @StartDate VARCHAR(10),
    @EndDate VARCHAR(10),
    @FunctionName VARCHAR(25) AS DECLARE @CalcFactor FLOAT BEGIN
SET
    NOCOUNT ON;

CREATE TABLE #TmpRatioData 
(
    ENTRYDATE DATETIME,
    FUNDCODE VARCHAR(25),
    INDICES VARCHAR(100),
    INDICESCLOSING FLOAT,
    INDICESPER FLOAT,
    FUNDCLOSING FLOAT,
    FUNDPER FLOAT,
    INCEPTIONDATE DATETIME,
    RISKFREERETURN FLOAT,
    FUNDTERM FLOAT
) CREATE TABLE #FINALRATIODATA
(
    FUNDCODE VARCHAR(25),
    MEANAVERAGE FLOAT NULL,
    RETURNVALUENAV FLOAT NULL,
    RETURNVALUEINDEX FLOAT NULL,
    CAGRVALUE FLOAT NULL,
    BETAVALUE FLOAT NULL,
    JENSENVALUE FLOAT NULL,
    SHARPEVALUE FLOAT NULL,
    TRACKINGVALUE FLOAT NULL,
    INFVALUE FLOAT NULL,
    STDEVVALUE FLOAT NULL,
    RSQUAREVALUE FLOAT NULL,
    TREYNORVALUE FLOAT NULL,
    SKEWVALUE FLOAT NULL,
    KURTOSISVALUE FLOAT NULL,
    COEFFVARVALUE FLOAT NULL,
    RISKADJVALUE FLOAT NULL
)
INSERT INTO
    #TmpRatioData (ENTRYDATE, FUNDCODE, INDICES, 
    INDICESCLOSING,
    INDICESPER,
    FUNDCLOSING,
    FUNDPER,
    INCEPTIONDATE,
    RISKFREERETURN,
    FUNDTERM
)
SELECT
    FUNDTABLE.ENTRYDATE,
    FUNDTABLE.FUNDCODE,
    TBINDICESDETAIL.INDICESNAME,
    TBINDICESDETAIL.CLOSINGVALUE AS INDICESCLOSING,
    TBINDICESDETAIL.PERCENTAGECHANGE AS INDICESPER,
    FUNDTABLE.FUNDCLOSING,
    FUNDTABLE.FUNDPER,
    FUNDTABLE.INCEPTIONDATE,
    FUNDTABLE.RISKFREERETURN,
    CAST(
        DATEDIFF(
            DAY,
            FUNDTABLE.INCEPTIONDATE,
            CONVERT(DATETIME, @EndDate, 103)
        ) AS DECIMAL(10, 5)
    ) / 365 AS FUNDTERM
FROM
    TBINDICESDETAIL
    INNER JOIN (
        SELECT
            TBFUNDDETAIL.ENTRYDATE,
            TBFUNDDETAIL.FUNDCODE,
            X.INDICESNAME,
            TBFUNDDETAIL.CLOSINGNAV AS FUNDCLOSING,
            TBFUNDDETAIL.PERCENTAGECHANGE AS FUNDPER,
            X.INCEPTIONDATE,
            X.RISKFREERETURN
        FROM
            TBFUNDDETAIL
            INNER JOIN (
                SELECT
                    FISOURCE.FUNDCODE,
                    FISOURCE.INDICESNAME,
                    FISOURCE.RISKFREERETURN,
                    "INCEPTIONDATE" = CASE
                        WHEN FISOURCE.FUNDOPENING <= FISOURCE.INDICESOPENING THEN FISOURCE.INDICESOPENING
                        WHEN FISOURCE.FUNDOPENING > FISOURCE.INDICESOPENING THEN FISOURCE.FUNDOPENING
                    END,
                    "TERM" = CASE
                        WHEN FISOURCE.FUNDOPENING <= FISOURCE.INDICESOPENING THEN DATEDIFF(
                            DAY,
                            FISOURCE.FUNDOPENING,
                            CONVERT(DATETIME, @EndDate, 103)
                        )
                        WHEN FISOURCE.FUNDOPENING > FISOURCE.INDICESOPENING THEN DATEDIFF(
                            DAY,
                            FISOURCE.INDICESOPENING,
                            CONVERT(DATETIME, @EndDate, 103)
                        )
                    END
                FROM
                    (
                        SELECT
                            FMASTER.FUNDCODE,
                            IMASTER.INDICESNAME,
                            FMASTER.RISKFREERETURN,
                            "FUNDOPENING" = CASE
                                WHEN FMASTER.FUNDOPDATE < CONVERT(DATETIME, @StartDate, 103) THEN CONVERT(DATETIME, @StartDate, 103)
                                WHEN FMASTER.FUNDOPDATE >= CONVERT(DATETIME, @StartDate, 103) THEN FMASTER.FUNDOPDATE
                            END,
                            "INDICESOPENING" = CASE
                                WHEN IMASTER.INDICESOPDATE < CONVERT(DATETIME, @StartDate, 103) THEN CONVERT(DATETIME, @StartDate, 103)
                                WHEN IMASTER.INDICESOPDATE >= CONVERT(DATETIME, @StartDate, 103) THEN IMASTER.INDICESOPDATE
                            END
                        FROM
                            (
                                SELECT
                                    FUNDCODE,
                                    INDICESNAME,
                                    RISKFREERETURN,
                                    OPDATE AS FUNDOPDATE
                                FROM
                                    TBFUNDMASTER
                                WHERE
                                    TBFUNDMASTER.FUNDCODE IN (
                                        SELECT
                                            FUNDCODE
                                        FROM
                                            #TmpFundCodes) AND TBFUNDMASTER.OPDATE < = CONVERT(DATETIME, @StartDate,103)) FMASTER INNER JOIN 
                                            (
                                                SELECT
                                                    INDICESNAME,
                                                    MIN(ENTRYDATE) AS INDICESOPDATE
                                                FROM
                                                    TBINDICESDETAIL
                                                GROUP BY
                                                    INDICESNAME
                                            ) IMASTER ON FMASTER.INDICESNAME = IMASTER.INDICESNAME
                                    ) FISOURCE
                            ) X ON TBFUNDDETAIL.FUNDCODE = X.FUNDCODE
                        WHERE
                            TBFUNDDETAIL.ENTRYDATE >= X.INCEPTIONDATE
                            AND TBFUNDDETAIL.ENTRYDATE < = CONVERT(DATETIME, @EndDate, 103)
                            AND TBFUNDDETAIL.HOLIDAY = 0
                    ) FUNDTABLE ON TBINDICESDETAIL.INDICESNAME = FUNDTABLE.INDICESNAME
                    AND TBINDICESDETAIL.ENTRYDATE = FUNDTABLE.ENTRYDATE
                WHERE
                    TBINDICESDETAIL.ENTRYDATE >= FUNDTABLE.INCEPTIONDATE
                    AND TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EndDate, 103)
                    AND TBINDICESDETAIL.HOLIDAY = 0
                SET
                    @CalcFactor = DATEDIFF(
                        DAY,
                        CONVERT(DATETIME, @StartDate, 103),
                        CONVERT(DATETIME, @EndDate, 103)
                    ) IF @CalcFactor > 365
                SET
                    @CalcFactor = @CalcFactor / 365
                    ELSE
                SET
                    @CalcFactor = 1 IF @FunctionName = 'BETA' BEGIN EXEC SpReturnBeta
                SELECT
                    TBFUNDMASTER.FUNDCODE,
                    TBFUNDMASTER.NAMEOFFUND,
                    #FINALRATIODATA.BETAVALUE AS RATIO FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
                    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.BETAVALUE ASC
            END IF @FunctionName = 'RETURNS' --CAGR to be included (Compunded Annual Growth rate)
            BEGIN EXEC SpReturnNAV 1,
            @CalcFactor EXEC SpReturnCAGR @CalcFactor
        SELECT
            TBFUNDMASTER.FUNDCODE,
            TBFUNDMASTER.NAMEOFFUND,
            #FINALRATIODATA.RETURNVALUENAV, #FINALRATIODATA.CAGRVALUE FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
            ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.RETURNVALUENAV DESC
    END IF @FunctionName = 'JENSEN' BEGIN EXEC SpReturnBeta EXEC SpReturnNAV 2,
    @CalcFactor EXEC SpReturnINDEX 2,
    @CalcFactor EXEC SpReturnJensen
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.JENSENVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.JENSENVALUE DESC
END IF @FunctionName = 'SHARPE' BEGIN EXEC SpReturnSharpe
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.SHARPEVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.SHARPEVALUE DESC
END IF @FunctionName = 'TRACKINGERROR' BEGIN EXEC SpReturnTrackingError
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.TRACKINGVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.TRACKINGVALUE ASC
END IF @FunctionName = 'INFRATIO' BEGIN EXEC SpReturnInformationRatio
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.INFVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.INFVALUE DESC
END IF @FunctionName = 'STDDEV' BEGIN EXEC SpReturnStandardDeviation 1
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.STDEVVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.STDEVVALUE ASC
END IF @FunctionName = 'RSQUARE' BEGIN EXEC SpReturnRSquare
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.RSQUAREVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.RSQUAREVALUE DESC
END IF @FunctionName = 'TREYNOR' BEGIN EXEC SpReturnBeta EXEC SpReturnTreynor
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.TREYNORVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE ORDER BY #FINALRATIODATA.TREYNORVALUE DESC
END IF @FunctionName = 'SKEWNESS' BEGIN EXEC SpReturnSkewness
SELECT
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.SKEWVALUE AS RATIO FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE 
ORDER BY
    #FINALRATIODATA.SKEWVALUE
END IF @FunctionName = 'KURTOSIS' BEGIN EXEC SpReturnKurtosis
SELECT
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.KURTOSISVALUE AS RATIO FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE 
ORDER BY
    #FINALRATIODATA.KURTOSISVALUE
END IF @FunctionName = 'COEFFVAR' BEGIN EXEC SpReturnMeanAverage EXEC SpReturnStandardDeviation 2 EXEC SpReturnCoEffVar
SELECT
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.COEFFVARVALUE AS RATIO FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE 
ORDER BY
    #FINALRATIODATA.COEFFVARVALUE
END
END