USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnCoEffVar]    Script Date: 01-03-2022 19:44:05 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnCoEffVar]

 AS  

BEGIN 


/* MAIN CALCULATION OF RETURN */


		UPDATE #FINALRATIODATA SET #FINALRATIODATA.COEFFVARVALUE = X.COEFFVAR FROM 		

		(SELECT FUNDCODE, ((STDEVVALUE / MEANAVERAGE) * 100) AS COEFFVAR FROM #FINALRATIODATA WHERE STDEVVALUE <> 0) X INNER JOIN 
			#FINALRATIODATA ON #FINALRATIODATA.FUNDCODE = X.FUNDCODE		
	
END
