USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnKurtosis]    Script Date: 01-03-2022 19:42:44 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnKurtosis]

AS  

BEGIN 

/* MAIN CALCULATION OF KURTOSIS */	


   		INSERT INTO #FINALRATIODATA (FUNDCODE, KURTOSISVALUE) 
			
			SELECT Y.FUNDCODE,
				 "KURTOSIS" =
						(SELECT (SUMXXXX - 4 * SUMXXX * AVX + 6 * SUMXX * AVX * AVX - 4 * SUMX * AVX * AVX * AVX + CNX * AVX * AVX * AVX * AVX) / 
						(SDX * SDX * SDX * SDX)  * CNX * (CNX + 1) / (CNX - 1) / (CNX - 2) / (CNX - 3)  - 3.0 * (CNX -1) * (CNX -1) / (CNX -2) / (CNX -3))
			 FROM 
			
			(SELECT 
				   X.FUNDCODE,
				   SUM(RFREEINDEX) AS SUMX, 
				   SUM(RFREEINDEX * RFREEINDEX) AS SUMXX,
				   SUM(RFREEINDEX * RFREEINDEX * RFREEINDEX) AS SUMXXX,
				   SUM(RFREEINDEX * RFREEINDEX * RFREEINDEX * RFREEINDEX) AS SUMXXXX,
				   COUNT(RFREEINDEX) AS CNX,
				   STDEV(RFREEINDEX) AS SDX,
				   AVG(RFREEINDEX) AS AVX FROM

		 (SELECT #TmpRatioData.FUNDCODE, ((#TmpRatioData.FUNDPER - #TmpRatioData.INDICESPER) - (#TmpRatioData.RISKFREERETURN/365)) AS RFREEINDEX  FROM #TmpRatioData) X
		 GROUP BY X.FUNDCODE) Y

END
