USE [MYPLEXUSDB_70803_COPY]
GO
/****** Object:  StoredProcedure [dbo].[SpSnapshotMonthlyBestFund]    Script Date: 25-02-2022 11:59:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SpSnapshotMonthlyBestFund]

@EntryDate		VARCHAR(10)

 AS
BEGIN
	SET NOCOUNT ON;	
		SELECT TOP 10 FINALDATA.NAMEOFFUND, FINALDATA.TYPENAME, FINALDATA.WEEKLY_CHANGE FROM
		(SELECT TBFUNDMASTER.NAMEOFFUND, TBFUNDTYPE.TYPENAME,
		"WEEKLY_CHANGE" = CASE 
		WHEN Z.PREVVALUE <= 0 THEN 0
		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100
		END
		FROM
		(SELECT X.FUNDCODE, X.PREVVALUE, Y.CURVALUE FROM 
		(SELECT CLOSINGNAV AS PREVVALUE, FUNDCODE FROM TBFUNDDETAIL
		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(MONTH, -1, CONVERT(DATETIME, @EntryDate, 103)))X
		INNER JOIN
		(SELECT CLOSINGNAV AS CURVALUE, FUNDCODE FROM TBFUNDDETAIL
		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y
		ON X.FUNDCODE = Y.FUNDCODE)Z INNER JOIN TBFUNDMASTER ON Z.FUNDCODE = TBFUNDMASTER.FUNDCODE
		INNER JOIN TBFUNDTYPE ON TBFUNDMASTER.FUNDTYPEID = TBFUNDTYPE.FUNDTYPEID
		) FINALDATA ORDER BY FINALDATA.WEEKLY_CHANGE DESC

END
