USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpWeeklyIndices]    Script Date: 02-03-2022 11:01:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SpWeeklyIndices] 

@EntryDate		VARCHAR(10),
@TypeID		INT
-- @TermID		INT


AS

BEGIN

SET NOCOUNT ON;

	CREATE TABLE #ReturnLessIndex
	    (
		INDICESNAME		VARCHAR(100) null,
		DAYS7			FLOAT null,
		DAYS14		FLOAT null,
		DAYS30		FLOAT null,
		DAYS60		FLOAT null
	    )


		INSERT INTO #ReturnLessIndex (INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60)

		SELECT  X.INDICESNAME, 
		"AVG7" 
		      = CASE 
		        WHEN X.STARTING7 <> 0 THEN ((X.CLOSING7 - X.STARTING7) / X.STARTING7) * 100
		        WHEN X.STARTING7 = 0 THEN 0
		        END,
		
		"AVG14" 
		      = CASE 
		        WHEN X.STARTING14 <> 0 THEN ((X.CLOSING14 - X.STARTING14) / X.STARTING14) * 100
		        WHEN X.STARTING14 = 0 THEN 0
		        END,
		
		"AVG30" 
		      = CASE 
		        WHEN X.STARTING30 <> 0 THEN ((X.CLOSING30 - X.STARTING30) / X.STARTING30) * 100
		        WHEN X.STARTING30 = 0 THEN 0
		        END,
		
		"AVG60" 
		      = CASE 
		        WHEN X.STARTING60 <> 0 THEN ((X.CLOSING60 - X.STARTING60) / X.STARTING60) * 100
		        WHEN X.STARTING60 = 0 THEN 0
		        END
		
		FROM
		   
		 (SELECT Y.INDICESNAME, 
		  
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING7,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING7,
		   
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING14,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING14,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING30,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING30,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING60,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING60
		
		   FROM (SELECT DISTINCT TBINDICESDETAIL.INDICESNAME, MIN(TBINDICESDETAIL.ENTRYDATE) AS OPDATE FROM TBINDICESDETAIL INNER JOIN 
				TBFUNDMASTER ON TBINDICESDETAIL.INDICESNAME = TBFUNDMASTER.INDICESNAME
				WHERE TBINDICESDETAIL.ENTRYDATE < CONVERT(DATETIME, @EntryDate, 103) 
				-- AND TBFUNDMASTER.FUNDTERMID = @TermID
				AND TBFUNDMASTER.FUNDTYPEID = @TypeID GROUP BY TBINDICESDETAIL.INDICESNAME) Y) X


		SELECT INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60 FROM #ReturnLessIndex ORDER BY INDICESNAME


END
