USE [MYPLEXUSDB_70803_COPY]
GO
	/****** Object:  StoredProcedure [dbo].[Sp_FundCompositionClassificationFree_New]    Script Date: 25-02-2022 11:16:47 ******/
SET
	ANSI_NULLS ON
GO
SET
	QUOTED_IDENTIFIER ON
GO
	--exec Sp_FundCompositionClassificationFree_New 51
	ALTER PROCEDURE [dbo].[Sp_FundCompositionClassificationFree_New] @TypeID INT AS DECLARE @SmallCapHVal BIGINT,
	@SmallCapLVal BIGINT,
	@MidCapHVal BIGINT,
	@MidCapLVal BIGINT,
	@LargeCapHVal BIGINT,
	@LargeCapLVal BIGINT,
	@VLargeCapHVal BIGINT,
	@VLargeCapLVal BIGINT,
	@EntryMonth INT,
	@EntryYear BIGINT,
	@LastDate DATETIME BEGIN
SET
	NOCOUNT ON;

CREATE TABLE #TmpComposition
(
	FUNDCODE VARCHAR(50),
	SUMCASH FLOAT,
	SUMSOV FLOAT,
	SUMDEBT FLOAT,
	SUMEQSMALL FLOAT,
	SUMEQMID FLOAT,
	SUMEQLARGE FLOAT,
	SUMEQVLARGE FLOAT,
	SUMEPS FLOAT
) CREATE TABLE #TMP_INDICES_COMPOSITION
(
	SCRIPNAME NVARCHAR(800),
	TYPE NVARCHAR(800),
	INDUSTRY NVARCHAR(800),
	PERCENTAGE FLOAT
) CREATE TABLE #TMP_INDICES_OTHER
(SCRIPNAME NVARCHAR(800)) CREATE TABLE #TMP_INDICES_COMPOSITION_RANK
(
	RANK INT IDENTITY (1, 1),
	SCRIPNAME NVARCHAR(800),
	Status VARCHAR(3) NOT NULL DEFAULT 'SC'
) CREATE TABLE #TMP_FUND_PORTFOLIO
(
	FUNDCODE NVARCHAR(100),
	SCRIPNAME NVARCHAR(800),
	MARKETCAP FLOAT,
	CONTENTPER FLOAT,
	PE FLOAT,
	Status VARCHAR(3) NULL
)
SET
	@LastDate = (
		SELECT
			TOP 1 ENTRYDATE
		FROM
			TbFundComposition
		ORDER BY
			EntryDate DESC
	)
SET
	@EntryMonth = MONTH(@LastDate)
SET
	@EntryYear = YEAR(@LastDate)
INSERT INTO
	#TMP_INDICES_COMPOSITION 
	EXEC SpIndicesComposition @EntryMonth,
	@EntryYear,
	'BSE 500'
INSERT INTO
	#TMP_INDICES_COMPOSITION_RANK
	(SCRIPNAME)
SELECT
	SCRIPNAME
FROM
	#TMP_INDICES_COMPOSITION 
WHERE
	[TYPE] = 'Equity'
ORDER BY
	PERCENTAGE DESC
UPDATE
	#TMP_INDICES_COMPOSITION_RANK
SET
	Status = 'VLC'
WHERE
	RANK BETWEEN 1
	AND 15
UPDATE
	#TMP_INDICES_COMPOSITION_RANK
SET
	Status = 'LC'
WHERE
	RANK BETWEEN 16
	AND 100
UPDATE
	#TMP_INDICES_COMPOSITION_RANK
SET
	Status = 'MC'
WHERE
	RANK BETWEEN 101
	AND 250
UPDATE
	#TMP_INDICES_COMPOSITION_RANK
SET
	Status = 'SC'
WHERE
	RANK > 250
INSERT INTO
	#TMP_INDICES_OTHER
	EXEC SpIndicesComposition_other @EntryMonth,
	@EntryYear
DELETE FROM
	#TMP_INDICES_OTHER WHERE SCRIPNAME IN (SELECT DISTINCT SCRIPNAME FROM #TMP_INDICES_COMPOSITION_RANK)
INSERT INTO
	#TMP_INDICES_COMPOSITION_RANK
	(SCRIPNAME, Status)
SELECT
	SCRIPNAME,
	'SC'
FROM
	#TMP_INDICES_OTHER		
INSERT INTO
	#TmpComposition 
	(
		FUNDCODE,
		SUMCASH,
		SUMSOV,
		SUMDEBT,
		SUMEQSMALL,
		SUMEQMID,
		SUMEQLARGE,
		SUMEQVLARGE,
		SUMEPS
	)
SELECT
	FUNDCODE,
	SUMCASH = 0,
	SUMSOV = 0,
	SUMDEBT = 0,
	SUMEQSMALL = 0,
	SUMEQMID = 0,
	SUMEQLARGE = 0,
	SUMEQVLARGE = 0,
	SUMEPS = 0
FROM
	TBFUNDMASTER
WHERE
	TBFUNDMASTER.FUNDTYPEID = @TypeID
UPDATE
	#TmpComposition 
SET
	SUMCASH = X.SUMOFCASH
FROM
	(
		SELECT
			FUNDCODE,
			SUM(CONTENTPER) AS SUMOFCASH
		FROM
			TBFUNDCOMPOSITION
		WHERE
			MONTH(ENTRYDATE) = @EntryMonth
			AND YEAR(ENTRYDATE) = @EntryYear
			AND CATEGORY = 'CASH'
		GROUP BY
			FUNDCODE
	) X
	INNER JOIN #TmpComposition T ON T.FUNDCODE = X.FUNDCODE
UPDATE
	#TmpComposition 
SET
	SUMSOV = X.SUMOFSOV
FROM
	(
		SELECT
			FUNDCODE,
			SUM(CONTENTPER) AS SUMOFSOV
		FROM
			TBFUNDCOMPOSITION
		WHERE
			MONTH(ENTRYDATE) = @EntryMonth
			AND YEAR(ENTRYDATE) = @EntryYear
			AND CATEGORY = 'SOV'
		GROUP BY
			FUNDCODE
	) X
	INNER JOIN #TmpComposition T ON T.FUNDCODE = X.FUNDCODE
UPDATE
	#TmpComposition 
SET
	SUMDEBT = X.SUMOFDEBT
FROM
	(
		SELECT
			FUNDCODE,
			SUM(CONTENTPER) AS SUMOFDEBT
		FROM
			TBFUNDCOMPOSITION
		WHERE
			MONTH(ENTRYDATE) = @EntryMonth
			AND YEAR(ENTRYDATE) = @EntryYear
			AND CATEGORY = 'Corporate Debt'
		GROUP BY
			FUNDCODE
	) X
	INNER JOIN #TmpComposition T ON T.FUNDCODE = X.FUNDCODE
INSERT INTO
	#TMP_FUND_PORTFOLIO
	(
		FUNDCODE,
		SCRIPNAME,
		MARKETCAP,
		CONTENTPER,
		PE
	)
SELECT
	X.FUNDCODE,
	X.ScripName,
	Y.MARKETCAP,
	X.CONTENTPER,
	Y.PE
FROM
	(
		SELECT
			C.FUNDCODE,
			C.ENTRYDATE,
			C.SCRIPNAME,
			C.CONTENTPER
		FROM
			TBFUNDCOMPOSITION C
			INNER JOIN TBFUNDMASTER F ON C.FUNDCODE = F.FUNDCODE
		WHERE
			CATEGORY = 'EQUITY'
			AND MONTH(C.ENTRYDATE) = @EntryMonth
			AND YEAR(C.ENTRYDATE) = @EntryYear
			AND F.FUNDTYPEID = @TypeID
	) X
	LEFT JOIN TBMCAPEPS Y ON X.SCRIPNAME = Y.SCRIPNAME
	AND X.ENTRYDATE = Y.ENTRYDATE
ORDER BY
	X.FUNDCODE,
	X.ScripName --UPDATE	#TMP_FUND_PORTFOLIO SET PE = 100 WHERE ISNULL(PE,0) = 0
UPDATE
	#TMP_FUND_PORTFOLIO
SET
	Status = I.Status
FROM
	#TMP_FUND_PORTFOLIO P, 
	#TMP_INDICES_COMPOSITION_RANK I
WHERE
	P.SCRIPNAME = I.SCRIPNAME
UPDATE
	#TmpComposition SET 
	SUMEQSMALL = SUMEQSMALL + Z.SUMSCONT,
	SUMEQMID = SUMEQMID + Z.SUMMCONT,
	SUMEQLARGE = SUMEQLARGE + Z.SUMLCONT,
	SUMEQVLARGE = SUMEQVLARGE + Z.SUMVCONT,
	SUMEPS = SUMEPS + Z.EPSSUM
FROM
	(
		SELECT
			FUNDCODE,
			SUM(ISNULL(SMALLCONTENTPER, 0)) AS SUMSCONT,
			SUM(ISNULL(MIDCONTENTPER, 0)) AS SUMMCONT,
			SUM(ISNULL(LARGECONTENTPER, 0)) AS SUMLCONT,
			SUM(ISNULL(VLARGECONTENTPER, 0)) AS SUMVCONT,
			SUM(ISNULL(EPSVALUE, 0)) AS EPSSUM
		FROM
			(
				SELECT
					FUNDCODE,
					"SMALLCONTENTPER" = (
						CASE
							WHEN Status = 'SC' THEN CONTENTPER
						END
					),
					"MIDCONTENTPER" = (
						CASE
							WHEN Status = 'MC' THEN CONTENTPER
						END
					),
					"LARGECONTENTPER" = (
						CASE
							WHEN Status = 'LC' THEN CONTENTPER
						END
					),
					"VLARGECONTENTPER" = (
						CASE
							WHEN Status = 'VLC' THEN CONTENTPER
						END
					),
					"EPSVALUE" = (PE * CONTENTPER) / 100
				FROM
					#TMP_FUND_PORTFOLIO)FINALDATA
				GROUP BY
					FINALDATA.FUNDCODE
			) Z
			INNER JOIN #TmpComposition T ON T.FUNDCODE = Z.FUNDCODE
		SELECT
			F.NAMEOFFUND,
			T.SUMCASH,
			T.SUMSOV,
			T.SUMDEBT,
			T.SUMEQSMALL,
			T.SUMEQMID,
			T.SUMEQLARGE,
			T.SUMEQVLARGE,
			ROUND(T.SUMEPS, 2) AS SUMEPS,
			@EntryMonth AS MonthInfo,
			@EntryYear AS YearInfo
		FROM
			#TmpComposition T 
			INNER JOIN TBFUNDMASTER F ON T.FUNDCODE = F.FUNDCODE
		ORDER BY
			F.NAMEOFFUND
	END