USE [MYPLEXUSDB_70803]
GO
    /****** Object:  StoredProcedure [dbo].[Sp_PerformanceRatio]    Script Date: 02-03-2022 18:32:33 ******/
SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    ALTER PROCEDURE [dbo].[Sp_PerformanceRatio] @StartDate VARCHAR(10),
    @EndDate VARCHAR(10),
    @FunctionName VARCHAR(25),
    @RiskFreeReturn float AS BEGIN
SET
    NOCOUNT ON;

IF @FunctionName = 'SKEWNESS' BEGIN EXEC SpPerformanceRankingIndividual @StartDate,
@EndDate,
@FunctionName
END
else IF @FunctionName = 'KURTOSIS' BEGIN EXEC SpPerformanceRankingIndividual @StartDate,
@EndDate,
@FunctionName
END
ELSE IF @FunctionName = 'COEFFVAR' BEGIN EXEC SpPerformanceRankingIndividual @StartDate,
@EndDate,
@FunctionName
END
ELSE BEGIN DECLARE @FundCode NVARCHAR(50);

CREATE TABLE #FINALRATIODATA  
(
    FUNDCODE VARCHAR(25),
    COVAR FLOAT NULL,
    VARIANCE FLOAT NULL,
    RETURNVALUEINDEX FLOAT NULL,
    CAGRVALUE FLOAT NULL,
    BETAVALUE FLOAT NULL,
    JENSENVALUE FLOAT NULL,
    SHARPEVALUE FLOAT NULL,
    TRACKINGVALUE FLOAT NULL,
    INFVALUE FLOAT NULL,
    STDEVVALUE FLOAT NULL,
    RSQUAREVALUE FLOAT NULL,
    TREYNORVALUE FLOAT NULL,
    SKEWVALUE FLOAT NULL,
    KURTOSISVALUE FLOAT NULL,
    COEFFVARVALUE FLOAT NULL,
    RISKADJVALUE FLOAT NULL
) DECLARE CURSOR1 CURSOR FOR
SELECT
    c.FundCode
FROM
    #TmpFundCodes c   
    INNER JOIN TbFundMaster m ON c.FUNDCODE = m.FUNDCODE
where
    OpDate <= CONVERT(DATETIME, @StartDate, 103) OPEN CURSOR1 FETCH NEXT
FROM
    CURSOR1 INTO @FundCode WHILE @ @FETCH_STATUS = 0 BEGIN EXEC Sp_GetBeta1 @StartDate,
    @EndDate,
    @FundCode,
    @RiskFreeReturn FETCH NEXT
FROM
    CURSOR1 INTO @FundCode
END CLOSE CURSOR1 DEALLOCATE CURSOR1 IF @FunctionName = 'BETA' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.BETAVALUE AS RATIO   
FROM
    #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    BETAVALUE is not null
ORDER BY
    #FINALRATIODATA.BETAVALUE ASC  
END IF @FunctionName = 'RETURNS' --CAGR to be included (Compunded Annual Growth rate)  
BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.CAGRVALUE AS RATIO  
FROM
    #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    CAGRVALUE is not null
ORDER BY
    #FINALRATIODATA.CAGRVALUE DESC  
END IF @FunctionName = 'JENSEN' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.JENSENVALUE AS RATIO    
FROM
    #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    JENSENVALUE is not null
ORDER BY
    #FINALRATIODATA.JENSENVALUE DESC  
END IF @FunctionName = 'SHARPE' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.SHARPEVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    SHARPEVALUE is not null
ORDER BY
    #FINALRATIODATA.SHARPEVALUE DESC  
END IF @FunctionName = 'TRACKINGERROR' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.TRACKINGVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    TRACKINGVALUE is not null
ORDER BY
    #FINALRATIODATA.TRACKINGVALUE ASC  
END IF @FunctionName = 'INFRATIO' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.INFVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    INFVALUE is not null
ORDER BY
    #FINALRATIODATA.INFVALUE DESC  
END IF @FunctionName = 'STDDEV' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.STDEVVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    STDEVVALUE is not null
ORDER BY
    #FINALRATIODATA.STDEVVALUE ASC  
END IF @FunctionName = 'RSQUARE' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.RSQUAREVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    RSQUAREVALUE is not null
ORDER BY
    #FINALRATIODATA.RSQUAREVALUE DESC  
END IF @FunctionName = 'TREYNOR' BEGIN
SELECT
    TBFUNDMASTER.FUNDCODE,
    TBFUNDMASTER.NAMEOFFUND,
    #FINALRATIODATA.TREYNORVALUE AS RATIO  FROM #FINALRATIODATA INNER JOIN TBFUNDMASTER  
    ON #FINALRATIODATA.FUNDCODE = TBFUNDMASTER.FUNDCODE   
where
    TREYNORVALUE is not null
ORDER BY
    #FINALRATIODATA.TREYNORVALUE DESC  
END
END
END