USE [MYPLEXUSDB_70803_COPY]
GO
/****** Object:  StoredProcedure [dbo].[Sp_SnapshotCHANGEVAL_NEW]    Script Date: 25-02-2022 12:06:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[Sp_SnapshotCHANGEVAL_NEW]
 
@EntryDate		VARCHAR(10),
@FundTypeID  INT,
@Days  INT

 
 AS
		DECLARE
		@CurFundType	VARCHAR(100),
		@CurMedian	FLOAT

BEGIN
 
		SELECT FINALDATA.FUNDCODE,k1.NameOfFund,FINALDATA.CHANGEVALUE  FROM

		(SELECT K.TYPENAME,K.FundTypeID,K.FUNDCODE,

		"CHANGEVALUE" = CASE 

		WHEN (Z.PREVVALUE <= 0 OR Z.CURVALUE <= 0) THEN 0

		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100

		END

		FROM

		(SELECT X.FUNDCODE, X.PREVVALUE, Y.CURVALUE FROM 

		(SELECT CLOSINGNAV AS PREVVALUE, FUNDCODE FROM TBFUNDDETAIL

		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(DAY, -@Days, CONVERT(DATETIME, @EntryDate, 103)))X

		INNER JOIN

		(SELECT CLOSINGNAV AS CURVALUE, FUNDCODE FROM TBFUNDDETAIL

		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y

		ON X.FUNDCODE = Y.FUNDCODE)Z INNER JOIN 

		((SELECT TBFUNDMASTER.FUNDCODE, TBFUNDTYPE.TYPENAME,TbFundType.FundTypeID  FROM TBFUNDMASTER 

		INNER JOIN TBFUNDTYPE ON TBFUNDMASTER.FUNDTYPEID = TBFUNDTYPE.FUNDTYPEID)) K ON Z.FUNDCODE = K.FUNDCODE) FINALDATA,
		TbFundMaster k1 where finaldata.fundcode=k1.fundcode and finaldata.FundTypeID=@FundTypeID
 
END
