USE [MYPLEXUSDB_70803_COPY]
GO
/****** Object:  StoredProcedure [dbo].[Sp_Snapshot_Indices_Currency_Commodity]    Script Date: 25-02-2022 11:48:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--exec Sp_Snapshot_Indices_Currency_Commodity 'GET_INDICES','05/01/2019',7
ALTER  PROCEDURE [dbo].[Sp_Snapshot_Indices_Currency_Commodity]

@FLAG VARCHAR(50)=NULL,
@EntryDate		VARCHAR(10)=NULL,
@Days		INT=0

AS
SET NOCOUNT ON;
IF UPPER(@FLAG)='GET_CURRENCY'
   BEGIN
		SELECT TBCURRENCYMASTER.CURRENCYID,TBCURRENCYMASTER.CURRENCYNAME,Z.CURVALUE,
		"PER_CHANGE" = CASE 
		WHEN Z.PREVVALUE <= 0 THEN 0
		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100
		END
		FROM
		(SELECT X.CURRENCYID, X.PREVVALUE, Y.CURVALUE FROM 
		(SELECT ENTRYVALUE AS PREVVALUE, CURRENCYID FROM TBCURRENCYDETAIL
		WHERE TBCURRENCYDETAIL.ENTRYDATE = DATEADD(DAY, -@Days, CONVERT(DATETIME, @EntryDate, 103)))X
		INNER JOIN
		(SELECT ENTRYVALUE AS CURVALUE, CURRENCYID FROM TBCURRENCYDETAIL
		WHERE TBCURRENCYDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y
		ON X.CURRENCYID = Y.CURRENCYID)Z INNER JOIN TBCURRENCYMASTER ON Z.CURRENCYID = TBCURRENCYMASTER.CURRENCYID
		WHERE TBCURRENCYMASTER.CURRENCYID = 2 OR TBCURRENCYMASTER.CURRENCYID = 3 OR TBCURRENCYMASTER.CURRENCYID = 5 
		ORDER BY TBCURRENCYMASTER.CURRENCYNAME


END		

ELSE IF UPPER(@FLAG)='GET_COMMODITY'
BEGIN	
	SELECT TBCURRENCYMASTER.CURRENCYID,TBCURRENCYMASTER.CURRENCYNAME,Z.CURVALUE,
		"PER_CHANGE" = CASE 
		WHEN Z.PREVVALUE <= 0 THEN 0
		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100
		END
		FROM
		(SELECT X.CURRENCYID, X.PREVVALUE, Y.CURVALUE FROM 
		(SELECT ENTRYVALUE AS PREVVALUE, CURRENCYID FROM TBCURRENCYDETAIL
		WHERE TBCURRENCYDETAIL.ENTRYDATE = DATEADD(DAY, -@Days, CONVERT(DATETIME, @EntryDate, 103)))X
		INNER JOIN
		(SELECT ENTRYVALUE AS CURVALUE, CURRENCYID FROM TBCURRENCYDETAIL
		WHERE TBCURRENCYDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y
		ON X.CURRENCYID = Y.CURRENCYID)Z INNER JOIN TBCURRENCYMASTER ON Z.CURRENCYID = TBCURRENCYMASTER.CURRENCYID
		WHERE TBCURRENCYMASTER.CURRENCYID = 1 OR TBCURRENCYMASTER.CURRENCYID = 4 OR  TBCURRENCYMASTER.CURRENCYID = 7 
		ORDER BY TBCURRENCYMASTER.CURRENCYNAME
END
	
ELSE IF UPPER(@FLAG)='GET_INDICES'
BEGIN
		CREATE TABLE #INDEXTABLE (
			INDEXNAME	VARCHAR(200)
		)

		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('S&P CNX Nifty Total Return Index')
		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('S&P CNX 500')
		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('BSE Sensex')
		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('BSE MidCap')
		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('S&P CNX Nifty Junior')
		INSERT INTO #INDEXTABLE (INDEXNAME) VALUES ('BSE 200')


		SELECT Z.INDICESNAME,Z.CURVALUE,
		"PER_CHANGE" = CASE 
		WHEN Z.PREVVALUE <= 0 THEN 0
		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100
		END
		FROM
		(SELECT X.INDICESNAME, X.PREVVALUE, Y.CURVALUE FROM 
		(SELECT CLOSINGVALUE AS PREVVALUE, INDICESNAME FROM TBINDICESDETAIL
		WHERE TBINDICESDETAIL.ENTRYDATE = DATEADD(DAY, -@Days, CONVERT(DATETIME, @EntryDate, 103)))X
		INNER JOIN
		(SELECT CLOSINGVALUE AS CURVALUE, INDICESNAME FROM TBINDICESDETAIL
		WHERE TBINDICESDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y
		ON X.INDICESNAME = Y.INDICESNAME)Z 
		WHERE Z.INDICESNAME IN (SELECT INDEXNAME FROM #INDEXTABLE)
		ORDER BY Z.INDICESNAME
END
