USE [MYPLEXUSDB_70803]
GO
    /****** Object:  StoredProcedure [dbo].[SpFundSearchCatDecile]    Script Date: 03-03-2022 15:19:19 ******/
SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    ALTER PROCEDURE [dbo].[SpFundSearchCatDecile] @StartDate VARCHAR(10),
    @EndDate VARCHAR(10),
    --@FundTypeID		INT,
    @FundCodeInput varchar(50) AS BEGIN DECLARE @FunctionName VARCHAR(10);

SET
    @FunctionName = 'RETURNS'
SET
    NOCOUNT ON;

CREATE TABLE #QUARTILEDATA
(
    FUNDCODE VARCHAR(25) null,
    COMPVALUE FLOAT null,
    QUARTILE INT null
) --DECLARE @EndDate		VARCHAR(10);
--SET @EndDate = DATEADD(DAY, -1, CONVERT(DATETIME, @StartDate, 103))
DECLARE @FundCode varchar(50) CREATE TABLE #FINALRATIODATA
(
    FUNDCODE VARCHAR(25),
    COVAR FLOAT NULL,
    VARIANCE FLOAT NULL,
    RETURNVALUEINDEX FLOAT NULL,
    CAGRVALUE FLOAT NULL,
    BETAVALUE FLOAT NULL,
    JENSENVALUE FLOAT NULL,
    SHARPEVALUE FLOAT NULL,
    TRACKINGVALUE FLOAT NULL,
    INFVALUE FLOAT NULL,
    STDEVVALUE FLOAT NULL,
    RSQUAREVALUE FLOAT NULL,
    TREYNORVALUE FLOAT NULL,
    SKEWVALUE FLOAT NULL,
    KURTOSISVALUE FLOAT NULL,
    COEFFVARVALUE FLOAT NULL,
    RISKADJVALUE FLOAT NULL
)
/*DECLARE CURSOR1 CURSOR  FOR SELECT m.FundCode 	
 FROM TbFundMaster m
 where OpDate<=CONVERT(DATETIME, @StartDate, 103)	
 and FundTypeID =@FundTypeID		
 OPEN CURSOR1				
 
 FETCH NEXT FROM CURSOR1 INTO @FundCode				
 
 WHILE @@FETCH_STATUS = 0
 BEGIN	*/
EXEC Sp_GetQuartileDecile @StartDate,
@EndDate,
@FundCodeInput,
6.5
/*FETCH NEXT FROM CURSOR1 INTO @FundCode		
 
 END
 CLOSE CURSOR1
 DEALLOCATE CURSOR1*/
IF @FunctionName = 'RETURNS' --CAGR to be included (Compunded Annual Growth rate)
BEGIN
INSERT INTO
    #QUARTILEDATA (FUNDCODE, COMPVALUE) 
SELECT
    #FINALRATIODATA.FUNDCODE, #FINALRATIODATA.CAGRVALUE FROM #FINALRATIODATA
where
    CAGRVALUE is not null
END EXEC SpDecileCompute;

SELECT
    TBFUNDMASTER.NAMEOFFUND,
    #QUARTILEDATA.COMPVALUE,  #QUARTILEDATA.QUARTILE FROM #QUARTILEDATA INNER JOIN TBFUNDMASTER
    ON #QUARTILEDATA.FUNDCODE = TBFUNDMASTER.FUNDCODE and #QUARTILEDATA.FUNDCODE = @FundCodeInput
END