USE [MYPLEXUSDB_70803]
GO
    /****** Object:  StoredProcedure [dbo].[SpFundSearchCatLeadLagWithName]    Script Date: 03-03-2022 15:21:11 ******/
SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    ALTER PROCEDURE [dbo].[SpFundSearchCatLeadLagWithName] @EntryDate VARCHAR(10),
    @FundTypeID INT AS DECLARE @FundCode varchar(50) BEGIN
SET
    NOCOUNT ON;

CREATE TABLE #TmpCatLag
(
    NAMEOFFUND VARCHAR(100),
    INDICESNAME VARCHAR(100),
    SEVENDAYS FLOAT,
    FORTEENDAYS FLOAT,
    THIRTYDAYS FLOAT,
    SIXTYDAYS FLOAT,
    NINTYDAYS FLOAT,
    SIXMONTHS FLOAT,
    ONEYEAR FLOAT,
    TWOYEAR FLOAT,
    THREEYEAR FLOAT,
    FIVEYEAR FLOAT
) CREATE TABLE #TmpCatLagOut
(
    --NAMEOFFUND		VARCHAR(100),
    --INDICESNAME     VARCHAR(100),
    SEVENDAYS FLOAT,
    THIRTYDAYS FLOAT,
    NINTYDAYS FLOAT,
    SIXMONTHS FLOAT,
    ONEYEAR FLOAT,
    TWOYEAR FLOAT,
    THREEYEAR FLOAT,
    FIVEYEAR FLOAT,
    SEVENDAYS_G FLOAT,
    THIRTYDAYS_G FLOAT,
    NINTYDAYS_G FLOAT,
    SIXMONTHS_G FLOAT,
    ONEYEAR_G FLOAT,
    TWOYEAR_G FLOAT,
    THREEYEAR_G FLOAT,
    FIVEYEAR_G FLOAT,
    SEVENDAYS_NAME VARCHAR(100),
    THIRTYDAYS_NAME VARCHAR(100),
    NINTYDAYS_NAME VARCHAR(100),
    SIXMONTHS_NAME VARCHAR(100),
    ONEYEAR_NAME VARCHAR(100),
    TWOYEAR_NAME VARCHAR(100),
    THREEYEAR_NAME VARCHAR(100),
    FIVEYEAR_NAME VARCHAR(100),
    SEVENDAYS_G_NAME VARCHAR(100),
    THIRTYDAYS_G_NAME VARCHAR(100),
    NINTYDAYS_G_NAME VARCHAR(100),
    SIXMONTHS_G_NAME VARCHAR(100),
    ONEYEAR_G_NAME VARCHAR(100),
    TWOYEAR_G_NAME VARCHAR(100),
    THREEYEAR_G_NAME VARCHAR(100),
    FIVEYEAR_G_NAME VARCHAR(100)
) DECLARE QUARTILECURSOR CURSOR FOR
SELECT
    FUNDCODE
FROM
    TBFUNDMASTER
WHERE
    FUNDTYPEID = @FundTypeID OPEN QUARTILECURSOR FETCH NEXT
FROM
    QUARTILECURSOR INTO @FundCode WHILE @ @FETCH_STATUS = 0 BEGIN
INSERT INTO
    #TmpCatLag 
    EXEC SpFundSearchSchemeRet @EntryDate,
    @FundCode FETCH NEXT
FROM
    QUARTILECURSOR INTO @FundCode
END CLOSE QUARTILECURSOR DEALLOCATE QUARTILECURSOR --SELECT * FROM #TmpCatLag
INSERT INTO
    #TmpCatLagOut(SEVENDAYS,THIRTYDAYS,NINTYDAYS,SIXMONTHS,ONEYEAR,TWOYEAR,THREEYEAR,FIVEYEAR,SEVENDAYS_G,THIRTYDAYS_G,NINTYDAYS_G,SIXMONTHS_G,ONEYEAR_G,TWOYEAR_G,THREEYEAR_G,FIVEYEAR_G,SEVENDAYS_NAME	,
    THIRTYDAYS_NAME,
    NINTYDAYS_NAME,
    SIXMONTHS_NAME,
    ONEYEAR_NAME,
    TWOYEAR_NAME,
    THREEYEAR_NAME,
    FIVEYEAR_NAME,
    SEVENDAYS_G_NAME,
    THIRTYDAYS_G_NAME,
    NINTYDAYS_G_NAME,
    SIXMONTHS_G_NAME,
    ONEYEAR_G_NAME,
    TWOYEAR_G_NAME,
    THREEYEAR_G_NAME,
    FIVEYEAR_G_NAME
)
VALUES
    (
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' ',
        ' '
    );

UPDATE
    #TmpCatLagOut SET SEVENDAYS = (SELECT TOP 1 SEVENDAYS FROM #TmpCatLag where SEVENDAYS<>0 ORDER BY SEVENDAYS DESC)
UPDATE
    #TmpCatLagOut SET THIRTYDAYS = (SELECT TOP 1  THIRTYDAYS FROM #TmpCatLag where THIRTYDAYS<>0  ORDER BY THIRTYDAYS DESC)
UPDATE
    #TmpCatLagOut SET NINTYDAYS = (SELECT TOP 1  NINTYDAYS FROM #TmpCatLag where NINTYDAYS<>0  ORDER BY NINTYDAYS DESC)
UPDATE
    #TmpCatLagOut SET SIXMONTHS = (SELECT TOP 1  SIXMONTHS FROM #TmpCatLag where SIXMONTHS<>0  ORDER BY SIXMONTHS DESC)
UPDATE
    #TmpCatLagOut SET ONEYEAR = (SELECT TOP 1  ONEYEAR FROM #TmpCatLag where ONEYEAR<>0  ORDER BY ONEYEAR DESC)
UPDATE
    #TmpCatLagOut SET TWOYEAR = (SELECT TOP 1 TWOYEAR FROM #TmpCatLag where TWOYEAR<>0  ORDER BY TWOYEAR DESC)
UPDATE
    #TmpCatLagOut SET THREEYEAR = (SELECT TOP 1 THREEYEAR FROM #TmpCatLag where THREEYEAR<>0  ORDER BY THREEYEAR DESC)
UPDATE
    #TmpCatLagOut SET FIVEYEAR = (SELECT TOP 1 FIVEYEAR FROM #TmpCatLag where FIVEYEAR<>0  ORDER BY FIVEYEAR DESC)
UPDATE
    #TmpCatLagOut SET SEVENDAYS_G = (SELECT TOP 1 SEVENDAYS FROM #TmpCatLag where SEVENDAYS<>0  ORDER BY SEVENDAYS ASC)
UPDATE
    #TmpCatLagOut SET THIRTYDAYS_G = (SELECT TOP 1  THIRTYDAYS FROM #TmpCatLag where THIRTYDAYS<>0  ORDER BY THIRTYDAYS ASC)
UPDATE
    #TmpCatLagOut SET NINTYDAYS_G = (SELECT TOP 1  NINTYDAYS FROM #TmpCatLag where NINTYDAYS<>0  ORDER BY NINTYDAYS ASC)
UPDATE
    #TmpCatLagOut SET SIXMONTHS_G = (SELECT TOP 1  SIXMONTHS FROM #TmpCatLag where SIXMONTHS<>0  ORDER BY SIXMONTHS ASC)
UPDATE
    #TmpCatLagOut SET ONEYEAR_G = (SELECT TOP 1  ONEYEAR FROM #TmpCatLag where ONEYEAR<>0  ORDER BY ONEYEAR ASC)
UPDATE
    #TmpCatLagOut SET TWOYEAR_G = (SELECT TOP 1 TWOYEAR FROM #TmpCatLag where TWOYEAR<>0  ORDER BY TWOYEAR ASC)
UPDATE
    #TmpCatLagOut SET THREEYEAR_G = (SELECT TOP 1 THREEYEAR FROM #TmpCatLag where THREEYEAR<>0  ORDER BY THREEYEAR ASC)
UPDATE
    #TmpCatLagOut SET FIVEYEAR_G = (SELECT TOP 1 FIVEYEAR FROM #TmpCatLag where FIVEYEAR<>0  ORDER BY FIVEYEAR ASC)
UPDATE
    #TmpCatLagOut SET SEVENDAYS_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where SEVENDAYS<>0  ORDER BY SEVENDAYS DESC)
UPDATE
    #TmpCatLagOut SET THIRTYDAYS_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where THIRTYDAYS<>0  ORDER BY THIRTYDAYS DESC)
UPDATE
    #TmpCatLagOut SET NINTYDAYS_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where NINTYDAYS<>0  ORDER BY NINTYDAYS DESC)
UPDATE
    #TmpCatLagOut SET SIXMONTHS_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where SIXMONTHS<>0  ORDER BY SIXMONTHS DESC)
UPDATE
    #TmpCatLagOut SET ONEYEAR_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where ONEYEAR<>0  ORDER BY ONEYEAR DESC)
UPDATE
    #TmpCatLagOut SET TWOYEAR_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where TWOYEAR<>0  ORDER BY TWOYEAR DESC)
UPDATE
    #TmpCatLagOut SET THREEYEAR_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where THREEYEAR<>0  ORDER BY THREEYEAR DESC)
UPDATE
    #TmpCatLagOut SET FIVEYEAR_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag  where FIVEYEAR<>0 ORDER BY FIVEYEAR DESC)
UPDATE
    #TmpCatLagOut SET SEVENDAYS_G_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where SEVENDAYS<>0  ORDER BY SEVENDAYS ASC)
UPDATE
    #TmpCatLagOut SET THIRTYDAYS_G_NAME = (SELECT TOP 1  NAMEOFFUND FROM #TmpCatLag where THIRTYDAYS<>0  ORDER BY THIRTYDAYS ASC)
UPDATE
    #TmpCatLagOut SET NINTYDAYS_G_NAME = (SELECT TOP 1  NAMEOFFUND FROM #TmpCatLag where NINTYDAYS<>0  ORDER BY NINTYDAYS ASC)
UPDATE
    #TmpCatLagOut SET SIXMONTHS_G_NAME = (SELECT TOP 1  NAMEOFFUND FROM #TmpCatLag where SIXMONTHS<>0  ORDER BY SIXMONTHS ASC)
UPDATE
    #TmpCatLagOut SET ONEYEAR_G_NAME = (SELECT TOP 1  NAMEOFFUND FROM #TmpCatLag where ONEYEAR<>0  ORDER BY ONEYEAR ASC)
UPDATE
    #TmpCatLagOut SET TWOYEAR_G_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where TWOYEAR<>0  ORDER BY TWOYEAR ASC)
UPDATE
    #TmpCatLagOut SET THREEYEAR_G_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where THREEYEAR<>0  ORDER BY THREEYEAR ASC)
UPDATE
    #TmpCatLagOut SET FIVEYEAR_G_NAME = (SELECT TOP 1 NAMEOFFUND FROM #TmpCatLag where FIVEYEAR<>0  ORDER BY FIVEYEAR ASC)
SELECT
    *
FROM
    #TmpCatLagOut
END