USE [MYPLEXUSDB_70803]
GO
    /****** Object:  StoredProcedure [dbo].[SpFundSearchCatAVGMED]    Script Date: 03-03-2022 15:21:59 ******/
SET
    ANSI_NULLS ON
GO
SET
    QUOTED_IDENTIFIER ON
GO
    ALTER PROCEDURE [dbo].[SpFundSearchCatAVGMED] @EntryDate VARCHAR(10),
    @FundTypeID INT AS DECLARE @FundCode varchar(50) BEGIN
SET
    NOCOUNT ON;

CREATE TABLE #TmpCatAVGMED
(
    NAMEOFFUND VARCHAR(100),
    INDICESNAME VARCHAR(100),
    SEVENDAYS FLOAT,
    FORTEENDAYS FLOAT,
    THIRTYDAYS FLOAT,
    SIXTYDAYS FLOAT,
    NINTYDAYS FLOAT,
    SIXMONTHS FLOAT,
    ONEYEAR FLOAT,
    TWOYEAR FLOAT,
    THREEYEAR FLOAT,
    FIVEYEAR FLOAT
) CREATE TABLE #TmpCatAVGMEDOut
(
    --NAMEOFFUND		VARCHAR(100),
    --INDICESNAME     VARCHAR(100),
    SEVENDAYS FLOAT,
    FORTEENDAYS FLOAT,
    THIRTYDAYS FLOAT,
    SIXTYDAYS FLOAT,
    NINTYDAYS FLOAT,
    SIXMONTHS FLOAT,
    ONEYEAR FLOAT,
    TWOYEAR FLOAT,
    THREEYEAR FLOAT,
    FIVEYEAR FLOAT,
    SEVENDAYS_G FLOAT,
    FORTEENDAYS_G FLOAT,
    THIRTYDAYS_G FLOAT,
    SIXTYDAYS_G FLOAT,
    NINTYDAYS_G FLOAT,
    SIXMONTHS_G FLOAT,
    ONEYEAR_G FLOAT,
    TWOYEAR_G FLOAT,
    THREEYEAR_G FLOAT,
    FIVEYEAR_G FLOAT
) DECLARE QUARTILECURSOR CURSOR FOR
SELECT
    FUNDCODE
FROM
    TBFUNDMASTER
WHERE
    FUNDTYPEID = @FundTypeID OPEN QUARTILECURSOR FETCH NEXT
FROM
    QUARTILECURSOR INTO @FundCode WHILE @ @FETCH_STATUS = 0 BEGIN
INSERT INTO
    #TmpCatAVGMED 
    EXEC SpFundSearchSchemeRet @EntryDate,
    @FundCode FETCH NEXT
FROM
    QUARTILECURSOR INTO @FundCode
END CLOSE QUARTILECURSOR DEALLOCATE QUARTILECURSOR --		select * from #TmpCatAVGMED ;
INSERT INTO
    #TmpCatAVGMEDOut(SEVENDAYS,THIRTYDAYS,NINTYDAYS,SIXMONTHS,ONEYEAR,TWOYEAR,THREEYEAR,FIVEYEAR,SEVENDAYS_G,THIRTYDAYS_G,NINTYDAYS_G,SIXMONTHS_G,ONEYEAR_G,TWOYEAR_G,THREEYEAR_G,FIVEYEAR_G)
VALUES
    (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

UPDATE
    #TmpCatAVGMEDOut SET SEVENDAYS = (SELECT AVG(SEVENDAYS) FROM #TmpCatAVGMED)
UPDATE
    #TmpCatAVGMEDOut SET THIRTYDAYS = (SELECT AVG(THIRTYDAYS) FROM #TmpCatAVGMED)
UPDATE
    #TmpCatAVGMEDOut SET NINTYDAYS = (SELECT AVG(NINTYDAYS) FROM #TmpCatAVGMED)
UPDATE
    #TmpCatAVGMEDOut SET SIXMONTHS = (SELECT AVG(SIXMONTHS) FROM #TmpCatAVGMED)
UPDATE
    #TmpCatAVGMEDOut SET ONEYEAR = (SELECT AVG(ONEYEAR) FROM #TmpCatAVGMED  where ONEYEAR<>0)
UPDATE
    #TmpCatAVGMEDOut SET TWOYEAR = (SELECT AVG(TWOYEAR) FROM #TmpCatAVGMED  where TWOYEAR<>0)
UPDATE
    #TmpCatAVGMEDOut SET THREEYEAR = (SELECT AVG(THREEYEAR) FROM #TmpCatAVGMED  where THREEYEAR<>0)
UPDATE
    #TmpCatAVGMEDOut SET FIVEYEAR = (SELECT AVG(FIVEYEAR) FROM #TmpCatAVGMED  where FIVEYEAR<>0)
UPDATE
    #TmpCatAVGMEDOut SET SEVENDAYS_G = (SELECT MAX(X.SEVENDAYS) FROM (SELECT TOP 50 PERCENT SEVENDAYS FROM #TmpCatAVGMED order by SEVENDAYS  )X)
UPDATE
    #TmpCatAVGMEDOut SET THIRTYDAYS_G = (SELECT MAX(X.THIRTYDAYS) FROM  (SELECT TOP 50 PERCENT THIRTYDAYS FROM #TmpCatAVGMED  order by THIRTYDAYS )X)
UPDATE
    #TmpCatAVGMEDOut SET NINTYDAYS_G = (SELECT MAX(X.NINTYDAYS) FROM (SELECT TOP 50 PERCENT NINTYDAYS FROM #TmpCatAVGMED  order by NINTYDAYS )X)
UPDATE
    #TmpCatAVGMEDOut SET SIXMONTHS_G = (SELECT MAX(X.SIXMONTHS) FROM (SELECT TOP 50 PERCENT SIXMONTHS FROM #TmpCatAVGMED  order by SIXMONTHS )X)
UPDATE
    #TmpCatAVGMEDOut SET ONEYEAR_G = (SELECT MAX(X.ONEYEAR) FROM (SELECT TOP 50 PERCENT ONEYEAR FROM #TmpCatAVGMED where ONEYEAR<>0   order by ONEYEAR )X)
UPDATE
    #TmpCatAVGMEDOut SET TWOYEAR_G = (SELECT MAX(X.TWOYEAR) FROM (SELECT TOP 50 PERCENT TWOYEAR FROM #TmpCatAVGMED where TWOYEAR<>0  order by ONEYEAR )X)
UPDATE
    #TmpCatAVGMEDOut SET THREEYEAR_G =(SELECT MAX(X.THREEYEAR) FROM  (SELECT TOP 50 PERCENT THREEYEAR FROM #TmpCatAVGMED where THREEYEAR<>0 order by ONEYEAR )X)
UPDATE
    #TmpCatAVGMEDOut SET FIVEYEAR_G = (SELECT MAX(X.FIVEYEAR) FROM (SELECT TOP 50 PERCENT FIVEYEAR FROM #TmpCatAVGMED  where FIVEYEAR<>0 order by ONEYEAR )X)
SELECT
    *
FROM
    #TmpCatAVGMEDOut
END