USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpIndicesComposition]    Script Date: 28-02-2022 20:41:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SpIndicesComposition]

@MonthNo		INT,
@YearNo		INT,
@IndicesName		VARCHAR(100)

AS

BEGIN
SET NOCOUNT ON;
	SELECT SCRIPNAME, TYPE, INDUSTRY, PERCENTAGE FROM TBINDICESCOMPOSITION WHERE
		MONTH(ENTRYDATE) = @MonthNo AND YEAR(ENTRYDATE) = @YearNo AND INDICESNAME = @IndicesName
		ORDER BY SCRIPNAME
END
