USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpMonthlyAverage]    Script Date: 02-03-2022 10:58:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER  PROCEDURE [dbo].[SpMonthlyAverage]
 
@EntryDate	VARCHAR(10),

@TypeID	INT

-- @TermID	INT
 
 AS
 
BEGIN
SET NOCOUNT ON;

		SELECT X.NAMEOFFUND, 
		X.FUNDCODE,

		     X.INDICESNAME,

		    "SIXMONTHS" 

		      = CASE 

		        WHEN (X.STARTVALUE6 <> 0 AND CLOSINGVALUE6 <> 0) THEN (((X.CLOSINGVALUE6 - X.STARTVALUE6)/ X.STARTVALUE6)*100)

		        WHEN X.STARTVALUE6 = 0 THEN 0

		        END,

		    "ONEYEAR" 

		      = CASE 

		        WHEN (X.STARTVALUE1 <> 0 AND X.CLOSINGVALUE1 <> 0) THEN (((X.CLOSINGVALUE1 - X.STARTVALUE1)/ X.STARTVALUE1)*100)

		        WHEN X.STARTVALUE1 = 0 THEN 0

		        END,

/* (POWER((RETURNDATA.FUNDBOTTOM/RETURNDATA.FUNDTOP), 1/@Term) - 1) * 100 */
 
		    "TWOYEAR" 

		      = CASE 

		        WHEN (X.STARTVALUE2 <> 0 AND X.CLOSINGVALUE2 <> 0) THEN ((POWER((X.CLOSINGVALUE2/X.STARTVALUE2),0.5) - 1) * 100)

		        WHEN X.STARTVALUE2 = 0 THEN 0

		        END,

		    "THREEYEAR" 

		      = CASE 

		        WHEN (X.STARTVALUE3 <> 0 AND X.CLOSINGVALUE3 <> 0) THEN  ((POWER((X.CLOSINGVALUE3/X.STARTVALUE3),0.33) - 1) * 100)

		        WHEN X.STARTVALUE3 = 0 THEN 0

		        END

		

		    FROM

		

		   (SELECT Y.NAMEOFFUND, Y.FUNDCODE, Y.INDICESNAME, 

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -182, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -182, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE6,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -182, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -182, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103)  AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE6,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE1,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE1,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -730, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -730, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE2,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -730, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -730, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE2,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -1095, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -1095, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE3,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND
		 
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(DAY, -1095, CONVERT(DATETIME, @EntryDate, 103)) AND Y.OPDATE < DATEADD(DAY, -1095, CONVERT(DATETIME, @EntryDate, 103)) AND  

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE3
-- AND FUNDTERMID = @TermID
		

		     FROM (SELECT NAMEOFFUND, FUNDCODE, INDICESNAME, OPDATE FROM TBFUNDMASTER WHERE OPDATE < CONVERT(DATETIME, @EntryDate, 103) AND FUNDTYPEID = @TypeID ) Y) X

		     ORDER BY X.NAMEOFFUND
 
END
