USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpMonthlyReturnLessIndex]    Script Date: 01-03-2022 18:58:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER   PROCEDURE [dbo].[SpMonthlyReturnLessIndex] 

@EntryDate	VARCHAR(10),
@TypeID	INT
--    @TermID	INT

 AS

BEGIN

SET NOCOUNT ON;

	CREATE TABLE #ReturnLessFund
	    (
		FUNDNAME		VARCHAR(255) null,
		FUNDCODE		VARCHAR(255) null,
		INDICESNAME		VARCHAR(100) null,
		DAYS7			FLOAT null,
		DAYS14		FLOAT null,
		DAYS30		FLOAT null,
		DAYS60		FLOAT null
	    )


	CREATE TABLE #ReturnLessIndex
	    (
		INDICESNAME		VARCHAR(100) null,
		DAYS7			FLOAT null,
		DAYS14		FLOAT null,
		DAYS30		FLOAT null,
		DAYS60		FLOAT null
	    )


		INSERT INTO #ReturnLessFund (FUNDNAME,FUNDCODE, INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60) 

		SELECT X.NAMEOFFUND, 
		X.FUNDCODE, 
		     X.INDICESNAME,
		    "SIXMONTHS" 
		      = CASE 
		        WHEN X.STARTVALUE6 <> 0 THEN (((X.CLOSINGVALUE6 - X.STARTVALUE6)/ X.STARTVALUE6)*100)
		        WHEN X.STARTVALUE6 = 0 THEN 0
		        END,
		    "ONEYEAR" 
		      = CASE 
		        WHEN X.STARTVALUE1 <> 0 THEN (((X.CLOSINGVALUE1 - X.STARTVALUE1)/ X.STARTVALUE1)*100)
		        WHEN X.STARTVALUE1 = 0 THEN 0
		        END,

		    "TWOYEAR" 
		      = CASE 
		        WHEN X.STARTVALUE2 <> 0 THEN ((POWER((X.CLOSINGVALUE2/X.STARTVALUE2),0.5)-1)*100)
		        WHEN X.STARTVALUE2 = 0 THEN 0
		        END,
		    "THREEYEAR" 
		      = CASE 
		        WHEN X.STARTVALUE3 <> 0 THEN ((POWER((X.CLOSINGVALUE3/X.STARTVALUE3),0.33)-1)*100) 
		        WHEN X.STARTVALUE3 = 0 THEN 0
		        END

/*

		    "TWOYEAR" 
		      = CASE 
		        WHEN X.STARTVALUE2 <> 0 THEN (((((X.CLOSINGVALUE2 - X.STARTVALUE2)/ X.STARTVALUE2)) / 2) * 100)
		        WHEN X.STARTVALUE2 = 0 THEN 0
		        END,
		    "THREEYEAR" 
		      = CASE 
		        WHEN X.STARTVALUE3 <> 0 THEN  (((((X.CLOSINGVALUE2 - X.STARTVALUE2)/ X.STARTVALUE2)) / 3) * 100)
		        WHEN X.STARTVALUE3 = 0 THEN 0
		        END
*/

/* (POWER((RETURNDATA.FUNDBOTTOM/RETURNDATA.FUNDTOP), 1/@Term) - 1) * 100 */		
		    FROM
		
		   (SELECT Y.NAMEOFFUND, Y.FUNDCODE, Y.INDICESNAME, 
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Month, -6, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE6,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Month, -6, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE6,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE1,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE1,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE2,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE2,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE3,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND
		

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND  
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE3
		
		     FROM (SELECT NAMEOFFUND, FUNDCODE, INDICESNAME, OPDATE FROM TBFUNDMASTER WHERE OPDATE < CONVERT(DATETIME, @EntryDate, 103) AND FUNDTYPEID = @TypeID ) Y) X
-- AND FUNDTERMID = @TermID
		INSERT INTO #ReturnLessIndex (INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60)

		SELECT X.INDICESNAME, 
		"AVG6" 
		      = CASE 
		        WHEN X.STARTING6 <> 0 THEN ((X.CLOSING6 - X.STARTING6) / X.STARTING6) * 100
		        WHEN X.STARTING6 = 0 THEN 0
		        END,
		
		"AVG1" 
		      = CASE 
		        WHEN X.STARTING1 <> 0 THEN ((X.CLOSING1 - X.STARTING1) / X.STARTING1) * 100
		        WHEN X.STARTING1 = 0 THEN 0
		        END,
		
		"AVG2" 
		      = CASE 
		        WHEN X.STARTING2 <> 0 THEN ((POWER((X.CLOSING2/X.STARTING2),0.5)-1)*100) 
		        WHEN X.STARTING2 = 0 THEN 0
		        END,
		
		"AVG3" 
		      = CASE 
		        WHEN X.STARTING3 <> 0 THEN ((POWER((X.CLOSING3/X.STARTING3),0.33)-1)*100) 
		        WHEN X.STARTING3 = 0 THEN 0
		        END

/*

		"AVG2" 
		      = CASE 
		        WHEN X.STARTING2 <> 0 THEN (((X.CLOSING2 - X.STARTING2) / X.STARTING2) / 2) * 100
		        WHEN X.STARTING2 = 0 THEN 0
		        END,
		
		"AVG3" 
		      = CASE 
		        WHEN X.STARTING3 <> 0 THEN (((X.CLOSING3 - X.STARTING3) / X.STARTING3) / 3) * 100
		        WHEN X.STARTING3 = 0 THEN 0
		        END
*/
		
		FROM
		   
		 (SELECT Y.INDICESNAME, 
		  
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING6,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(MONTH, -6, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING6,
		   
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING1,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -1, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING1,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING2,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -2, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING2,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING3,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(YEAR, -3, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING3
		

		   FROM (SELECT DISTINCT TBINDICESDETAIL.INDICESNAME, MIN(TBINDICESDETAIL.ENTRYDATE) AS OPDATE FROM TBINDICESDETAIL INNER JOIN 
				TBFUNDMASTER ON TBINDICESDETAIL.INDICESNAME = TBFUNDMASTER.INDICESNAME
				WHERE TBINDICESDETAIL.ENTRYDATE < CONVERT(DATETIME, @EntryDate, 103) 
				-- AND TBFUNDMASTER.FUNDTERMID = @TermID
				AND TBFUNDMASTER.FUNDTYPEID = @TypeID GROUP BY TBINDICESDETAIL.INDICESNAME) Y) X
			

		SELECT #ReturnLessFund.FUNDNAME, #ReturnLessFund.FUNDCODE,
			"VALUES6" = CASE 
			 WHEN #ReturnLessFund.DAYS7 <> 0 AND #ReturnLessIndex.DAYS7 <> 0 THEN #ReturnLessFund.DAYS7 - #ReturnLessIndex.DAYS7
			 WHEN #ReturnLessFund.DAYS7 = 0 OR #ReturnLessIndex.DAYS7 = 0 THEN 0
			 END,
			"VALUES1" = CASE 
			 WHEN #ReturnLessFund.DAYS14 <> 0 AND #ReturnLessIndex.DAYS14 <> 0 THEN #ReturnLessFund.DAYS14 - #ReturnLessIndex.DAYS14
			 WHEN #ReturnLessFund.DAYS14 = 0 OR #ReturnLessIndex.DAYS14 = 0 THEN 0
			 END,
			"VALUES2" = CASE 
			 WHEN #ReturnLessFund.DAYS30 <> 0 AND #ReturnLessIndex.DAYS30 <> 0 THEN #ReturnLessFund.DAYS30 - #ReturnLessIndex.DAYS30
			 WHEN #ReturnLessFund.DAYS30 = 0 OR #ReturnLessIndex.DAYS30 = 0 THEN 0
			 END,
			"VALUES3" = CASE 
			 WHEN #ReturnLessFund.DAYS60 <> 0 AND #ReturnLessIndex.DAYS60 <> 0 THEN #ReturnLessFund.DAYS60 - #ReturnLessIndex.DAYS60
			 WHEN #ReturnLessFund.DAYS60 = 0 OR #ReturnLessIndex.DAYS60 = 0 THEN 0
			 END
		FROM #ReturnLessFund INNER JOIN #ReturnLessIndex ON #ReturnLessFund.INDICESNAME = #ReturnLessIndex.INDICESNAME ORDER BY #ReturnLessFund.FUNDNAME
		     



END
