USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpMonthlyCorpusChange]    Script Date: 02-03-2022 10:49:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER   PROCEDURE [dbo].[SpMonthlyCorpusChange]

@EntryDate		VARCHAR(10),
@TypeID		INT
--     @TermID		INT


AS
		DECLARE
		@PrevDate	DATETIME,
		@CurDate	DATETIME
BEGIN
SET NOCOUNT ON;

		SET @PrevDate = DATEADD(DAY, -1, DATEADD(MONTH, -1, DATEADD(DAY, 1, CONVERT(DATETIME, @EntryDate, 103))))
		
		SET @CurDate	=  CONVERT(DATETIME, @EntryDate, 103)

		SELECT TBFUNDMASTER.NAMEOFFUND,TBFUNDMASTER.FUNDCODE, FINALDATA.CURRENTVALUE, FINALDATA.DIFFVALUE, FINALDATA.CHANGEVALUE FROM 
		(SELECT X.FUNDCODE, 
		"CURRENTVALUE" = Y.CURVALUE 
		,
		"CHANGEVALUE" = CASE
		WHEN X.PREVVALUE > 0 THEN ((Y.CURVALUE - X.PREVVALUE) / X.PREVVALUE)  * 100
		ELSE  0
		END
		, 
		"DIFFVALUE"=CASE
		WHEN X.PREVVALUE > 0 THEN (Y.CURVALUE - X.PREVVALUE) 
		ELSE  0
		END
		FROM

		(SELECT TBCORPUSENTRY.CORPUSENTRY AS PREVVALUE, TBCORPUSENTRY.FUNDCODE FROM TBCORPUSENTRY WHERE
			 TBCORPUSENTRY.ENTRYDATE = @PrevDate)X INNER JOIN 

		(SELECT TBCORPUSENTRY.CORPUSENTRY AS CURVALUE, TBCORPUSENTRY.FUNDCODE FROM TBCORPUSENTRY WHERE
			 TBCORPUSENTRY.ENTRYDATE = @CurDate)Y ON X.FUNDCODE = Y.FUNDCODE) FINALDATA
		INNER JOIN TBFUNDMASTER ON FINALDATA.FUNDCODE = TBFUNDMASTER.FUNDCODE
		WHERE (TBFUNDMASTER.FUNDTYPEID = @TypeID )
		--      AND FUNDTERMID = @TermID
		ORDER BY FINALDATA.CHANGEVALUE DESC
		
		
END
