USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnRSquare]    Script Date: 01-03-2022 19:39:53 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnRSquare]

 AS  

BEGIN 


/* MAIN CALCULATION OF TRACKING ERROR */


		BEGIN
			INSERT INTO #FINALRATIODATA (FUNDCODE, RSQUAREVALUE)

				SELECT RSQUAREDATA.FUNDCODE, 
					"RSQUARE" = CASE

					WHEN (RSQUAREDATA.STDFUND * STDINDEX) <> 0 THEN ((RSQUAREDATA.COVAR / RSQUAREDATA.DATACOUNT) / (RSQUAREDATA.STDFUND * STDINDEX))
					WHEN (RSQUAREDATA.STDFUND * STDINDEX) = 0 THEN 0
					END

				FROM

				(SELECT FINALDATA.FUNDCODE, SUM(FINALDATA.CALCVALUES) AS COVAR, COUNT(FINALDATA.FUNDCODE) AS DATACOUNT,
					 STDEV(FINALDATA.FUNDCLOSING) AS STDFUND, STDEV(FINALDATA.INDICESCLOSING) AS STDINDEX

				FROM

				(SELECT DATASOURCE.FUNDCODE, DATASOURCE.FUNDCLOSING, DATASOURCE.INDICESCLOSING, 
					((DATASOURCE.FUNDCLOSING - DATASOURCE.AVGFUND) * (DATASOURCE.INDICESCLOSING - DATASOURCE.AVGINDEX)) AS CALCVALUES

				FROM

				(SELECT #TmpRatioData.FUNDCODE, #TmpRatioData.FUNDCLOSING, X.AVGFUND, #TmpRatioData.INDICESCLOSING, X.AVGINDEX  FROM #TmpRatioData INNER JOIN 

				(SELECT FUNDCODE, AVG(FUNDCLOSING) AS AVGFUND, AVG(INDICESCLOSING) AS AVGINDEX
				 FROM #TmpRatioData GROUP BY FUNDCODE)X ON #TmpRatioData.FUNDCODE = X.FUNDCODE) DATASOURCE) FINALDATA GROUP BY FINALDATA.FUNDCODE) RSQUAREDATA
				WHERE RSQUAREDATA.DATACOUNT <> 0
		    END

	
END
