USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnJensen]    Script Date: 01-03-2022 19:35:12 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnJensen]

 AS  

BEGIN 

 /* @EarningsOnPortFolioNAV - ((@RiskFreeReturn * @Term * 0.01) + @Beta  * (@EarningsOnPortFolioINDEX - (@RiskFreeReturn * @Term * 0.01))) */


	UPDATE #FINALRATIODATA SET #FINALRATIODATA.JENSENVALUE = 
		   (#FINALRATIODATA.RETURNVALUENAV/100) - 
		    ((JENSENDATA.RISKFREERETURN * JENSENDATA.FUNDTERM * 0.01) + #FINALRATIODATA.BETAVALUE * ((#FINALRATIODATA.RETURNVALUEINDEX/100) - (JENSENDATA.RISKFREERETURN * JENSENDATA.FUNDTERM * 0.01)))

		 FROM 

		(SELECT DISTINCT FUNDCODE, RISKFREERETURN, FUNDTERM FROM #TmpRatioData) JENSENDATA INNER JOIN #FINALRATIODATA
		 ON JENSENDATA.FUNDCODE = #FINALRATIODATA.FUNDCODE

END
