USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnStandardDeviation]    Script Date: 01-03-2022 19:39:04 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnStandardDeviation]

@InputType		INT

 AS  

BEGIN 


/* MAIN CALCULATION OF TRACKING ERROR */

	IF @InputType = 1 

		BEGIN
			INSERT INTO #FINALRATIODATA (FUNDCODE, STDEVVALUE)  
	
				SELECT RETURNDATA.FUNDCODE, STDEV(RETURNDATA.DAILYEXCESS) AS STDEVVALUE
				
				FROM
				
				(SELECT FUNDCODE, FUNDCLOSING AS DAILYEXCESS FROM #TmpRatioData) RETURNDATA GROUP BY RETURNDATA.FUNDCODE
		    END

	IF @InputType = 2

		BEGIN
			UPDATE #FINALRATIODATA SET STDEVVALUE = X.STDEVVALUE FROM 
	
				(SELECT RETURNDATA.FUNDCODE, STDEV(RETURNDATA.DAILYEXCESS) AS STDEVVALUE
				
				FROM
				
				(SELECT FUNDCODE, FUNDCLOSING AS DAILYEXCESS FROM #TmpRatioData) RETURNDATA GROUP BY RETURNDATA.FUNDCODE) X
				INNER JOIN #FINALRATIODATA ON X.FUNDCODE = #FINALRATIODATA.FUNDCODE

		    END
	
END
