USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnCAGR]    Script Date: 01-03-2022 19:33:48 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnCAGR]

@Term		FLOAT

 AS  

BEGIN 


/* MAIN CALCULATION OF CAGR */


	UPDATE #FINALRATIODATA SET CAGRVALUE = CAGRDATA.CAGRVALUE FROM  

		(SELECT RETURNDATA.FUNDCODE,
		"CAGRVALUE" = CASE 
		  WHEN  RETURNDATA.FUNDTOP <> 0 THEN (POWER((RETURNDATA.FUNDBOTTOM/RETURNDATA.FUNDTOP), 1/@Term) - 1) * 100
		  WHEN RETURNDATA.FUNDTOP = 0 THEN 0
		  END

		FROM

		(SELECT X.FUNDCODE,  
		(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
		WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE ASC) AS FUNDTOP,
		
		(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
		WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE DESC) AS FUNDBOTTOM
		
		FROM
		
		(SELECT DISTINCT FUNDCODE FROM #TmpRatioData)X) RETURNDATA) CAGRDATA INNER JOIN #FINALRATIODATA ON #FINALRATIODATA.FUNDCODE = CAGRDATA.FUNDCODE

	
END
