USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnNAV]    Script Date: 01-03-2022 19:33:12 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER    PROCEDURE [dbo].[SpReturnNAV]

@InputType	INT,
@Term		FLOAT

 AS  

BEGIN 


/* MAIN CALCULATION OF RETURN */

/* The InputType Parameter instructs whether to insert or to update data in the table */

	IF @InputType = 1 

		BEGIN

		     IF @Term <=1
			   BEGIN 	
				INSERT INTO #FINALRATIODATA (FUNDCODE, RETURNVALUENAV) 
		
					SELECT RETURNDATA.FUNDCODE, 
						"RETURNVALUE" = CASE
						 WHEN RETURNDATA.FUNDTOP <> 0 THEN (((RETURNDATA.FUNDBOTTOM - RETURNDATA.FUNDTOP) / RETURNDATA.FUNDTOP) / @Term) * 100
						 WHEN RETURNDATA.FUNDTOP = 0 THEN 0
						 END
		
					FROM
		
					(SELECT X.FUNDCODE,  
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE ASC) AS FUNDTOP,
					
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE DESC) AS FUNDBOTTOM
					
					FROM
					
					(SELECT DISTINCT FUNDCODE FROM #TmpRatioData)X) RETURNDATA
			    END
			ELSE
			   BEGIN 	
				INSERT INTO #FINALRATIODATA (FUNDCODE, RETURNVALUENAV) 
		
					SELECT RETURNDATA.FUNDCODE, 
						"RETURNVALUE" = CASE
						 WHEN RETURNDATA.FUNDTOP <> 0 THEN ((POWER((RETURNDATA.FUNDBOTTOM/RETURNDATA.FUNDTOP), 1/@Term) -1) * 100)
						 WHEN RETURNDATA.FUNDTOP = 0 THEN 0
						 END
		
					FROM
		
					(SELECT X.FUNDCODE,  
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE ASC) AS FUNDTOP,
					
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE DESC) AS FUNDBOTTOM
					
					FROM
					
					(SELECT DISTINCT FUNDCODE FROM #TmpRatioData)X) RETURNDATA
			    END

		    END

	IF @InputType = 2

		BEGIN

		    IF @Term <= 1
		       BEGIN
				UPDATE #FINALRATIODATA SET #FINALRATIODATA.RETURNVALUENAV = RETURNUPDATE.RETURNVALUE FROM 
		
					(SELECT RETURNDATA.FUNDCODE,
						"RETURNVALUE" = CASE
						 WHEN RETURNDATA.FUNDTOP <> 0 THEN ((RETURNDATA.FUNDBOTTOM - RETURNDATA.FUNDTOP) / RETURNDATA.FUNDTOP)  * 100
						 WHEN RETURNDATA.FUNDTOP = 0 THEN 0
						 END
		
					FROM
		
					(SELECT X.FUNDCODE,
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE ASC) AS FUNDTOP,
					
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE DESC) AS FUNDBOTTOM
					
					FROM
					
					(SELECT DISTINCT FUNDCODE FROM #TmpRatioData)X) RETURNDATA) RETURNUPDATE 
					INNER JOIN #FINALRATIODATA ON #FINALRATIODATA.FUNDCODE = RETURNUPDATE.FUNDCODE
			END
		      ELSE
		       BEGIN
				UPDATE #FINALRATIODATA SET #FINALRATIODATA.RETURNVALUENAV = RETURNUPDATE.RETURNVALUE FROM 
		
					(SELECT RETURNDATA.FUNDCODE,
						"RETURNVALUE" = CASE
						 WHEN RETURNDATA.FUNDTOP <> 0 THEN ((POWER((RETURNDATA.FUNDBOTTOM/RETURNDATA.FUNDTOP), 1/@Term) -1) * 100)
						 WHEN RETURNDATA.FUNDTOP = 0 THEN 0
						 END
		
					FROM
		
					(SELECT X.FUNDCODE,
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE ASC) AS FUNDTOP,
					
					(SELECT TOP 1 FUNDCLOSING FROM #TmpRatioData 
					WHERE #TmpRatioData.FUNDCODE = X.FUNDCODE ORDER BY ENTRYDATE DESC) AS FUNDBOTTOM
					
					FROM
					
					(SELECT DISTINCT FUNDCODE FROM #TmpRatioData)X) RETURNDATA) RETURNUPDATE 
					INNER JOIN #FINALRATIODATA ON #FINALRATIODATA.FUNDCODE = RETURNUPDATE.FUNDCODE
			END
		    END
	
	
END
