USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnInformationRatio]    Script Date: 01-03-2022 19:38:13 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnInformationRatio]

 AS  

BEGIN 


/* MAIN CALCULATION OF TRACKING ERROR */


		BEGIN
			INSERT INTO #FINALRATIODATA (FUNDCODE, INFVALUE)  

				SELECT DATASOURCE.FUNDCODE, 
					"TRACKINGERROR" = CASE 
					WHEN DATASOURCE.TRACKINGERROR <> 0 THEN  (DATASOURCE.AVGEXCESS/DATASOURCE.TRACKINGERROR)
					WHEN DATASOURCE.TRACKINGERROR = 0 THEN  0
					END
				FROM
	
				(SELECT RETURNDATA.FUNDCODE, STDEV(RETURNDATA.DAILYEXCESS) AS TRACKINGERROR, AVG(RETURNDATA.DAILYEXCESS) AS AVGEXCESS
				
				FROM
				
				(SELECT FUNDCODE, (FUNDPER - INDICESPER) AS DAILYEXCESS FROM #TmpRatioData) RETURNDATA GROUP BY RETURNDATA.FUNDCODE) DATASOURCE
		    END

	
END
