USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnSkewness]    Script Date: 01-03-2022 19:42:02 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnSkewness]

AS  

BEGIN 

/* MAIN CALCULATION OF SKEWNESS */	


   		INSERT INTO #FINALRATIODATA (FUNDCODE, SKEWVALUE) 
			
			SELECT Y.FUNDCODE,
				 "SKEWNESS" =
						  (SELECT (Y.SUMXXX - 3 * Y.SUMXX * Y.AVX + 3 * Y.SUMX * Y.AVX * Y.AVX - Y.CNX * Y.AVX * Y.AVX * Y.AVX) /
						   (Y.SDX * Y.SDX * Y.SDX) * Y.CNX / (Y.CNX - 1) / (Y.CNX - 2))
			 FROM 
			
			(SELECT 
				   X.FUNDCODE,
				   SUM(X.RFREEINDEX) AS SUMX, 
  				   SUM(X.RFREEINDEX * RFREEINDEX) AS SUMXX,
				   SUM(X.RFREEINDEX * RFREEINDEX * RFREEINDEX) AS SUMXXX,
				   COUNT(X.RFREEINDEX) AS CNX,
				   STDEV(X.RFREEINDEX) AS SDX,
				   AVG(X.RFREEINDEX) AS AVX FROM

		 (SELECT #TmpRatioData.FUNDCODE, ((#TmpRatioData.FUNDPER - #TmpRatioData.INDICESPER) - (#TmpRatioData.RISKFREERETURN/365)) AS RFREEINDEX  FROM #TmpRatioData) X
		 GROUP BY X.FUNDCODE) Y

END
