USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnMeanAverage]    Script Date: 01-03-2022 19:43:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnMeanAverage]

 AS  

BEGIN 


/* MAIN CALCULATION OF RETURN */


		INSERT INTO #FINALRATIODATA (FUNDCODE, MEANAVERAGE) 

		SELECT #TmpRatioData.FUNDCODE, AVG(#TmpRatioData.FUNDCLOSING) AS MEANAVGVALUE FROM #TmpRatioData GROUP BY #TmpRatioData.FUNDCODE
	
END
