USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnBeta]    Script Date: 01-03-2022 19:32:14 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnBeta]

 AS  

BEGIN 

	CREATE TABLE #SortedData
		(
			FUNDCODE		VARCHAR(25),
			ENTRYDATE		DATETIME,
			FUNDCLOSING		FLOAT,
			INDICESCLOSING	FLOAT
		)

	
	INSERT INTO #SortedData (FUNDCODE, ENTRYDATE, FUNDCLOSING, INDICESCLOSING) 

	SELECT DATASOURCEONE.FUNDCODE, DATASOURCEONE.ENTRYDATE, DATASOURCEONE.FUNDCLOSING, DATASOURCEONE.INDICESCLOSING
		FROM 
		(SELECT #TmpRatioData.FUNDCODE, #TmpRatioData.ENTRYDATE, #TmpRatioData.FUNDCLOSING, #TmpRatioData.INDICESCLOSING
		FROM #TmpRatioData,
		(SELECT FUNDCODE, MONTH(ENTRYDATE) AS MONTHNAME, YEAR(ENTRYDATE) AS YEARNAME FROM #TmpRatioData
		GROUP BY FUNDCODE, MONTH(ENTRYDATE), YEAR(ENTRYDATE))FUNDFILTER
		WHERE #TmpRatioData.FUNDCODE = FUNDFILTER.FUNDCODE AND 
		#TmpRatioData.ENTRYDATE IN 
		(SELECT MIN(#TmpRatioData.ENTRYDATE) FROM #TmpRatioData 
		 WHERE MONTH(#TmpRatioData.ENTRYDATE) = FUNDFILTER.MONTHNAME AND YEAR(#TmpRatioData.ENTRYDATE) = FUNDFILTER.YEARNAME
		AND #TmpRatioData.FUNDCODE = FUNDFILTER.FUNDCODE))DATASOURCEONE


/* MAIN CALCULATION OF BETA */

		INSERT INTO #FINALRATIODATA (FUNDCODE, BETAVALUE) 

		SELECT BETADATA.FUNDCODE,
			"BETAVALUE" = CASE
			WHEN BETADATA.BETABOTTOM <> 0 THEN BETADATA.BETATOP / BETADATA.BETABOTTOM
			WHEN BETADATA.BETABOTTOM  =  0 THEN 0
			END

			FROM

		(SELECT FINALBETA.FUNDCODE,
			"BETATOP" 		=  (FINALBETA.DATACOUNT * FINALBETA.INDEXNAV) - (FINALBETA.NAVSUM * FINALBETA.INDEXSUM),
			"BETABOTTOM" 	=  (FINALBETA.DATACOUNT * FINALBETA.NAVSQUARE) - (FINALBETA.NAVSUM * FINALBETA.NAVSUM)

			FROM

		(SELECT SEMIBETA.FUNDCODE,
			 "NAVSUM" 		= SUM(SEMIBETA.BETANAV),
			 "INDEXSUM"		= SUM(SEMIBETA.BETAINDEX),
			 "NAVSQUARE"	= SUM(SQUARE(SEMIBETA.BETANAV)),
			 "INDEXNAV"		= SUM(SEMIBETA.BETANAV * SEMIBETA.BETAINDEX),
			 "DATACOUNT"	= COUNT(SEMIBETA.BETANAV)

			FROM


		
		(SELECT DATASOURCETWO.FUNDCODE, DATASOURCETWO.ENTRYDATE,
			 "BETANAV" = CASE
			  WHEN DATASOURCETWO.PREVFUNDCLOSING <> 0 AND DATASOURCETWO.FUNDCLOSING <> 0 THEN ((DATASOURCETWO.FUNDCLOSING - DATASOURCETWO.PREVFUNDCLOSING) / DATASOURCETWO.PREVFUNDCLOSING) * 100
			  WHEN DATASOURCETWO.PREVFUNDCLOSING = 0 OR DATASOURCETWO.FUNDCLOSING = 0 THEN 0
			  END,
			 "BETAINDEX" = CASE
			  WHEN DATASOURCETWO.PREVINDEXCLOSING <> 0 AND DATASOURCETWO.INDICESCLOSING <> 0 THEN ((DATASOURCETWO.INDICESCLOSING - DATASOURCETWO.PREVINDEXCLOSING) / DATASOURCETWO.PREVINDEXCLOSING) * 100
			  WHEN DATASOURCETWO.PREVINDEXCLOSING = 0 OR DATASOURCETWO.INDICESCLOSING = 0 THEN 0
			  END

		         FROM

		(SELECT DATASOURCEONE.FUNDCODE, DATASOURCEONE.ENTRYDATE, DATASOURCEONE.FUNDCLOSING, DATASOURCEONE.INDICESCLOSING,
		            ISNULL((SELECT TOP 1 #SortedData.FUNDCLOSING FROM #SortedData WHERE  #SortedData.ENTRYDATE < DATASOURCEONE.ENTRYDATE
				AND #SortedData.FUNDCODE = DATASOURCEONE.FUNDCODE ORDER BY #SortedData.ENTRYDATE DESC),0) AS PREVFUNDCLOSING,

		            ISNULL((SELECT TOP 1 #SortedData.INDICESCLOSING FROM #SortedData WHERE  #SortedData.ENTRYDATE < DATASOURCEONE.ENTRYDATE
				AND #SortedData.FUNDCODE = DATASOURCEONE.FUNDCODE ORDER BY #SortedData.ENTRYDATE DESC),0) AS PREVINDEXCLOSING

		FROM 
		(SELECT #TmpRatioData.FUNDCODE, #TmpRatioData.ENTRYDATE, #TmpRatioData.FUNDCLOSING, #TmpRatioData.INDICESCLOSING
		FROM #TmpRatioData,
		(SELECT FUNDCODE, MONTH(ENTRYDATE) AS MONTHNAME, YEAR(ENTRYDATE) AS YEARNAME FROM #TmpRatioData
		GROUP BY FUNDCODE, MONTH(ENTRYDATE), YEAR(ENTRYDATE))FUNDFILTER
		WHERE #TmpRatioData.FUNDCODE = FUNDFILTER.FUNDCODE AND 
		#TmpRatioData.ENTRYDATE IN 
		(SELECT MIN(#TmpRatioData.ENTRYDATE) FROM #TmpRatioData 
		 WHERE MONTH(#TmpRatioData.ENTRYDATE) = FUNDFILTER.MONTHNAME AND YEAR(#TmpRatioData.ENTRYDATE) = FUNDFILTER.YEARNAME
		AND #TmpRatioData.FUNDCODE = FUNDFILTER.FUNDCODE))DATASOURCEONE) DATASOURCETWO) SEMIBETA GROUP BY SEMIBETA.FUNDCODE)FINALBETA) BETADATA
	
END
