USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnTreynor]    Script Date: 01-03-2022 19:41:06 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnTreynor]

 AS  

BEGIN 


/* MAIN CALCULATION OF TREYNOR  */

			UPDATE #FINALRATIODATA SET TREYNORVALUE = FINALDATA.AVGCALCPER / #FINALRATIODATA.BETAVALUE FROM 

			(SELECT TREYNORONE.FUNDCODE, AVG(TREYNORONE.CALCPER) AS AVGCALCPER FROM 

			(SELECT #TmpRatioData.FUNDCODE, (#TmpRatioData.FUNDPER - Y.FRISKFREE) AS CALCPER FROM #TmpRatioData INNER JOIN 

			 (SELECT X.FUNDCODE, ((X.RISKFREERETURN * 0.01) / 365) AS FRISKFREE FROM
			(SELECT DISTINCT FUNDCODE, RISKFREERETURN FROM #TmpRatioData) X ) Y ON #TmpRatioData.FUNDCODE = Y.FUNDCODE) TREYNORONE
			GROUP BY TREYNORONE.FUNDCODE) FINALDATA INNER JOIN #FINALRATIODATA ON #FINALRATIODATA.FUNDCODE = FINALDATA.FUNDCODE WHERE #FINALRATIODATA.BETAVALUE <> 0



	
END
