USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnSharpe]    Script Date: 01-03-2022 19:35:51 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnSharpe]

 AS  

BEGIN 


/* MAIN CALCULATION OF SHARPE */	

   		INSERT INTO #FINALRATIODATA (FUNDCODE, SHARPEVALUE) 

		SELECT CALCSHARPE.FUNDCODE, 
			 "SHARPEVALUE" = (CALCSHARPE.AVGEXCESSRISKFREE / CALCSHARPE.STDDEV)

		FROM

		(SELECT SEMISHARPE.FUNDCODE, AVG(SEMISHARPE.EXCESSRISKFREE) AS AVGEXCESSRISKFREE, SQRT(SEMISHARPE.FSTDDEV) AS STDDEV 
		
		FROM
		
		(SELECT XX.FUNDCODE, (XX.FUNDPER - XX.COMPUTEDRISKFREE) AS EXCESSRISKFREE,
			"FSTDDEV" = CASE 
			 WHEN (XX.DATACOUNT * (XX.DATACOUNT - 1)) <> 0 THEN ((XX.DATACOUNT * XX.SUMSQUARE) - XX.SQUARESUM) / (XX.DATACOUNT * (XX.DATACOUNT - 1)) 
			 WHEN (XX.DATACOUNT * (XX.DATACOUNT - 1)) = 0 THEN 0
			END
		FROM 

		(SELECT Z.FUNDCODE, Z.SUMSQUARE, Z.SQUARESUM, Z.DATACOUNT, Z.COMPUTEDRISKFREE, #TmpRatioData.FUNDPER

		FROM
		
		(SELECT Y.FUNDCODE, Y.SUMSQUARE, Y.SQUARESUM,

		"COMPUTEDRISKFREE"	= (SELECT TOP 1 (RISKFREERETURN * 0.01)/365 AS COMPUTEDRISKFREE FROM #TmpRatioData WHERE #TmpRatioData.FUNDCODE = Y.FUNDCODE),
		"DATACOUNT" 		= (SELECT COUNT(*) FROM #TmpRatioData WHERE #TmpRatioData.FUNDCODE = Y.FUNDCODE)

		 FROM

		(SELECT #TmpRatioData.FUNDCODE, SUM(SQUARE(#TmpRatioData.FUNDCLOSING)) AS SUMSQUARE, SQUARE(SUM(#TmpRatioData.FUNDCLOSING)) AS SQUARESUM
		FROM #TmpRatioData GROUP BY #TmpRatioData.FUNDCODE)Y)Z INNER JOIN #TmpRatioData ON Z.FUNDCODE = #TmpRatioData.FUNDCODE) XX) SEMISHARPE
		GROUP BY SEMISHARPE.FUNDCODE, SEMISHARPE.FSTDDEV) CALCSHARPE WHERE CALCSHARPE.STDDEV <> 0 
END
