USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpReturnTrackingError]    Script Date: 01-03-2022 19:36:50 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
ALTER  PROCEDURE [dbo].[SpReturnTrackingError]

 AS  

BEGIN 


/* MAIN CALCULATION OF TRACKING ERROR */


		BEGIN
			INSERT INTO #FINALRATIODATA (FUNDCODE, TRACKINGVALUE)  
	
				SELECT RETURNDATA.FUNDCODE, STDEV(RETURNDATA.DAILYEXCESS) AS TRACKINGERROR
				
				FROM
				
				(SELECT FUNDCODE, (FUNDPER - INDICESPER) AS DAILYEXCESS FROM #TmpRatioData) RETURNDATA GROUP BY RETURNDATA.FUNDCODE
		    END

	
END
