USE [MYPLEXUSDB_70803_COPY]
GO
/****** Object:  StoredProcedure [dbo].[SpSnapshotMonthlyBenchmark]    Script Date: 25-02-2022 11:51:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[SpSnapshotMonthlyBenchmark]
 
@EntryDate		VARCHAR(10)
 
 AS
		DECLARE
		@CurFundType	VARCHAR(100),
		@CurMedian	FLOAT

BEGIN
SET NOCOUNT ON;
 
		CREATE TABLE #FundTemp (

			FUNDTYPE		VARCHAR(100),
			CHANGEVAL		FLOAT,
			FundTypeID  INT

		)
		
		
		CREATE TABLE #NewFundTemp (
			FUNDTYPE		VARCHAR(100),
			MEANVAL			FLOAT,
			MEDIANVAL		FLOAT,
			FundTypeID  INT
		)
		

		INSERT INTO #FundTemp (FUNDTYPE, CHANGEVAL,FundTypeID) 

		SELECT FINALDATA.TYPENAME, FINALDATA.WEEKLY_CHANGE,FundTypeID FROM

		(SELECT K.TYPENAME,K.FundTypeID,

		"WEEKLY_CHANGE" = CASE 

		WHEN (Z.PREVVALUE <= 0 OR Z.CURVALUE <= 0) THEN 0

		ELSE ((Z.CURVALUE - Z.PREVVALUE)/Z.PREVVALUE) * 100

		END

		FROM

		(SELECT X.FUNDCODE, X.PREVVALUE, Y.CURVALUE FROM 

		(SELECT CLOSINGNAV AS PREVVALUE, FUNDCODE FROM TBFUNDDETAIL

		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103)))X

		INNER JOIN

		(SELECT CLOSINGNAV AS CURVALUE, FUNDCODE FROM TBFUNDDETAIL

		WHERE TBFUNDDETAIL.ENTRYDATE = DATEADD(DAY, -1, CONVERT(DATETIME, @EntryDate, 103)))Y

		ON X.FUNDCODE = Y.FUNDCODE)Z INNER JOIN 

		((SELECT TBFUNDMASTER.FUNDCODE, TBFUNDTYPE.TYPENAME,TbFundType.FundTypeID  FROM TBFUNDMASTER 

		INNER JOIN TBFUNDTYPE ON TBFUNDMASTER.FUNDTYPEID = TBFUNDTYPE.FUNDTYPEID)) K ON Z.FUNDCODE = K.FUNDCODE) FINALDATA
 
		--SELECT FUNDTYPE, AVG(CHANGEVAL) AS CHANGEVALUE FROM #FundTemp GROUP BY FUNDTYPE
		
		
		INSERT INTO #NewFundTemp SELECT FUNDTYPE, AVG(CHANGEVAL), 0,FundTypeID FROM #FundTemp GROUP BY FundTypeID,FUNDTYPE
 
		DECLARE FUND_CURSOR CURSOR FOR SELECT FUNDTYPE FROM #FundTemp GROUP BY FUNDTYPE
 
		

		OPEN FUND_CURSOR
 
		FETCH NEXT FROM FUND_CURSOR INTO @CurFundType
 
	        WHILE @@FETCH_STATUS = 0

		   BEGIN

                      SET @CurMedian = 0

  		      SET @CurMedian = 	

		      (SELECT MAX(X.CHANGEVAL) AS MEDIANVAL FROM

		      		(SELECT TOP 50 PERCENT CHANGEVAL FROM #FundTemp WHERE FUNDTYPE = @CurFundType ORDER BY CHANGEVAL)X)

                      UPDATE #NewFundTemp SET MEDIANVAL = @CurMedian WHERE FUNDTYPE = @CurFundType

		      FETCH NEXT FROM FUND_CURSOR INTO @CurFundType		    

		   END

		

		   CLOSE FUND_CURSOR

		   DEALLOCATE FUND_CURSOR
 
		SELECT FUNDTYPE, MEANVAL 'CHANGEVALUE', MEDIANVAL,FundTypeID FROM #NewFundTemp

END
