USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpWeeklyAverage]    Script Date: 02-03-2022 11:02:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SpWeeklyAverage]
 
@EntryDate	VARCHAR(10),

@TypeID	INT

-- @TermID	INT
 
 AS
 
BEGIN
SET NOCOUNT ON;
 
		SELECT X.NAMEOFFUND,
		X.FUNDCODE,

		     X.INDICESNAME,
			

		    "5DAYS" 

		      = CASE 

		        WHEN X.TOTCOUNT <> 0 THEN X.PCTSUM/X.TOTCOUNT

		      
			  WHEN X.TOTCOUNT = 0 THEN 0

		        END,

		    "7DAYS" 

		      = CASE 

		        WHEN (X.STARTVALUE7 <> 0 AND X.CLOSINGVALUE7 <> 0) THEN (((X.CLOSINGVALUE7 - X.STARTVALUE7)/ X.STARTVALUE7)*100)

		        WHEN X.STARTVALUE7 = 0 THEN 0

			  WHEN X.CLOSINGVALUE7 = 0 THEN 0


		        END,

		    "14DAYS" 

		      = CASE 

		        WHEN (X.STARTVALUE14 <> 0 AND X.CLOSINGVALUE14 <> 0) THEN (((X.CLOSINGVALUE14 - X.STARTVALUE14)/ X.STARTVALUE14)*100)

		        WHEN X.STARTVALUE14 = 0 THEN 0

		        END,

		    "30DAYS" 

		      = CASE 

		        WHEN (X.STARTVALUE30 <> 0 AND X.CLOSINGVALUE30 <> 0) THEN (((X.CLOSINGVALUE30 - X.STARTVALUE30)/ X.STARTVALUE30)*100)

		        WHEN X.STARTVALUE30 = 0 THEN 0

		        END,

		    "60DAYS" 

		      = CASE 

		        WHEN (X.STARTVALUE60 <> 0 AND X.CLOSINGVALUE60 <> 0) THEN (((X.CLOSINGVALUE60 - X.STARTVALUE60)/ X.STARTVALUE60)*100)

		        WHEN X.STARTVALUE60 = 0 THEN 0

		        END

		

		    FROM

		

		   (SELECT Y.NAMEOFFUND, Y.FUNDCODE, Y.INDICESNAME, 

		     ISNULL((SELECT Count(*) From TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND  
Y.OPDATE < DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

				TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

				TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND

				TBFUNDDETAIL.HOLIDAY = 0), 0) AS TOTCOUNT,

		      ISNULL((SELECT SUM(TBFUNDDETAIL.PERCENTAGECHANGE)

		      FROM TBFUNDDETAIL

		      WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND  Y.OPDATE < DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		      TBFUNDDETAIL.ENTRYDATE >= DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		      TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND

		      TBFUNDDETAIL.HOLIDAY = 0), 0) AS PCTSUM,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND  Y.OPDATE < DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE7,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND

		      Y.OPDATE < DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE7,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND  Y.OPDATE < DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE14,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND

		       Y.OPDATE < DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE14,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND  Y.OPDATE < DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE30,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND

                                 Y.OPDATE < DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE30,

		

		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 

		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE60,

		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND
		       Y.OPDATE < DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND

		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103)  AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE60

	--  AND FUNDTERMID = @TermID	

		     FROM (SELECT NAMEOFFUND, FUNDCODE, INDICESNAME, OPDATE FROM TBFUNDMASTER WHERE OPDATE < CONVERT(DATETIME, @EntryDate, 103) AND FUNDTYPEID = @TypeID) Y) X 

		     ORDER BY X.NAMEOFFUND
 
END