USE [MYPLEXUSDB_70803]
GO
/****** Object:  StoredProcedure [dbo].[SpWeeklyReturnLessIndex]    Script Date: 02-03-2022 11:00:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SpWeeklyReturnLessIndex]

@EntryDate	VARCHAR(10),
@TypeID	INT
-- @TermID	INT

AS

BEGIN
SET NOCOUNT ON;
	CREATE TABLE #ReturnLessFund
	    (
		FUNDNAME		VARCHAR(255) null,
		FUNDCODE		VARCHAR(255) null,
		INDICESNAME		VARCHAR(100) null,
		DAYS7			FLOAT null,
		DAYS14		FLOAT null,
		DAYS30		FLOAT null,
		DAYS60		FLOAT null
	    )

 
	CREATE TABLE #ReturnLessIndex
	    (
		INDICESNAME		VARCHAR(100),
		DAYS7			FLOAT,
		DAYS14		FLOAT,
		DAYS30		FLOAT,
		DAYS60		FLOAT
	    )


		INSERT INTO #ReturnLessFund (FUNDNAME,FUNDCODE, INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60) 

		SELECT X.NAMEOFFUND,X.FUNDCODE,   X.INDICESNAME,
		    "7DAYS" 
		      = CASE 
		        WHEN X.STARTVALUE7 <> 0 THEN (((X.CLOSINGVALUE7 - X.STARTVALUE7)/ X.STARTVALUE7)*100)
		        WHEN X.STARTVALUE7 = 0 THEN 0
		        END,
		    "14DAYS" 
		      = CASE 
		        WHEN X.STARTVALUE14 <> 0 THEN (((X.CLOSINGVALUE14 - X.STARTVALUE14)/ X.STARTVALUE14)*100)
		        WHEN X.STARTVALUE14 = 0 THEN 0
		        END,
		    "30DAYS" 
		      = CASE 
		        WHEN X.STARTVALUE30 <> 0 THEN (((X.CLOSINGVALUE30 - X.STARTVALUE30)/ X.STARTVALUE30)*100)
		        WHEN X.STARTVALUE30 = 0 THEN 0
		        END,
		    "60DAYS" 
		      = CASE 
		        WHEN X.STARTVALUE60 <> 0 THEN (((X.CLOSINGVALUE60 - X.STARTVALUE60)/ X.STARTVALUE60)*100)
		        WHEN X.STARTVALUE60 = 0 THEN 0
		        END
		
		    FROM
		
		   (SELECT Y.NAMEOFFUND, Y.FUNDCODE, Y.INDICESNAME, 
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE7,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -7, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE7,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE14,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -14, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE14,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE30,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -30, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE30,
		
		     ISNULL((SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL 
		     WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE),0) AS STARTVALUE60,
		    (SELECT TOP 1 TBFUNDDETAIL.CLOSINGNAV FROM TBFUNDDETAIL WHERE TBFUNDDETAIL.FUNDCODE = Y.FUNDCODE AND
		     Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		     TBFUNDDETAIL.ENTRYDATE > DATEADD(Day, -60, CONVERT(DATETIME, @EntryDate, 103)) AND
		     TBFUNDDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103)  AND TBFUNDDETAIL.HOLIDAY = 0 ORDER BY TBFUNDDETAIL.ENTRYDATE DESC) AS CLOSINGVALUE60
		
		     FROM (SELECT NAMEOFFUND, FUNDCODE, INDICESNAME, OPDATE FROM TBFUNDMASTER WHERE OPDATE < CONVERT(DATETIME, @EntryDate, 103) AND FUNDTYPEID = @TypeID ) Y) X
			 -- AND FUNDTERMID = @TermID
		INSERT INTO #ReturnLessIndex (INDICESNAME, DAYS7, DAYS14, DAYS30, DAYS60)

		SELECT  X.INDICESNAME, 
		"AVG7" 
		      = CASE 
		        WHEN X.STARTING7 <> 0 THEN ((X.CLOSING7 - X.STARTING7) / X.STARTING7) * 100
		        WHEN X.STARTING7 = 0 THEN 0
		        END,
		
		"AVG14" 
		      = CASE 
		        WHEN X.STARTING14 <> 0 THEN ((X.CLOSING14 - X.STARTING14) / X.STARTING14) * 100
		        WHEN X.STARTING14 = 0 THEN 0
		        END,
		
		"AVG30" 
		      = CASE 
		        WHEN X.STARTING30 <> 0 THEN ((X.CLOSING30 - X.STARTING30) / X.STARTING30) * 100
		        WHEN X.STARTING30 = 0 THEN 0
		        END,
		
		"AVG60" 
		      = CASE 
		        WHEN X.STARTING60 <> 0 THEN ((X.CLOSING60 - X.STARTING60) / X.STARTING60) * 100
		        WHEN X.STARTING60 = 0 THEN 0
		        END
		
		FROM
		   
		 (SELECT Y.INDICESNAME, 
		  
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING7,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -7, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING7,
		   
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING14,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -14, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING14,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING30,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -30, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING30,
		
		  ISNULL((SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE), 0) AS STARTING60,
		
		  (SELECT TOP 1 TBINDICESDETAIL.CLOSINGVALUE FROM TBINDICESDETAIL WHERE 
		   TBINDICESDETAIL.INDICESNAME = Y.INDICESNAME AND Y.OPDATE < DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103))  AND
		   TBINDICESDETAIL.ENTRYDATE > DATEADD(DAY, -60, CONVERT(DATETIME, @EntryDate, 103)) AND 
		   TBINDICESDETAIL.ENTRYDATE <= CONVERT(DATETIME, @EntryDate, 103) AND TBINDICESDETAIL.HOLIDAY = 0 ORDER BY TBINDICESDETAIL.ENTRYDATE DESC) AS CLOSING60
		
		   FROM (SELECT DISTINCT TBINDICESDETAIL.INDICESNAME, MIN(TBINDICESDETAIL.ENTRYDATE) AS OPDATE FROM TBINDICESDETAIL INNER JOIN 
				TBFUNDMASTER ON TBINDICESDETAIL.INDICESNAME = TBFUNDMASTER.INDICESNAME
				WHERE TBINDICESDETAIL.ENTRYDATE < CONVERT(DATETIME, @EntryDate, 103) 
				-- AND TBFUNDMASTER.FUNDTERMID = @TermID
				AND TBFUNDMASTER.FUNDTYPEID = @TypeID GROUP BY TBINDICESDETAIL.INDICESNAME) Y) X
			

		SELECT #ReturnLessFund.FUNDNAME,#ReturnLessFund.FUNDCODE,
			 (#ReturnLessFund.DAYS7 - #ReturnLessIndex.DAYS7) AS VALUES7,
			 (#ReturnLessFund.DAYS14 - #ReturnLessIndex.DAYS14) AS VALUES14,
			 (#ReturnLessFund.DAYS30 - #ReturnLessIndex.DAYS30) AS VALUES30,
			 (#ReturnLessFund.DAYS60 - #ReturnLessIndex.DAYS60) AS VALUES60

		FROM #ReturnLessFund INNER JOIN #ReturnLessIndex ON #ReturnLessFund.INDICESNAME = #ReturnLessIndex.INDICESNAME ORDER BY #ReturnLessFund.FUNDNAME
		     

END
