DELIMITER / / CREATE PROCEDURE sp_return_information_ratio() BEGIN
INSERT INTO
	final_ratio_data (fund_code, inf_value)
SELECT
	DATASOURCE.fund_code,
	CASE
		WHEN DATASOURCE.TRACKINGERROR <> 0 THEN (DATASOURCE.AVGEXCESS / DATASOURCE.TRACKINGERROR)
		WHEN DATASOURCE.TRACKINGERROR = 0 THEN 0
	END AS "TRACKINGERROR"
FROM
	(
		SELECT
			RETURNDATA.fund_code,
			STDEV(RETURNDATA.DAILYEXCESS) AS TRACKINGERROR,
			AVG(RETURNDATA.DAILYEXCESS) AS AVGEXCESS
		FROM
			(
				SELECT
					fund_code,
					(fund_per - indices_per) AS DAILYEXCESS
				FROM
					TmpRatioData
			) RETURNDATA
		GROUP BY
			RETURNDATA.fund_code
	) DATASOURCE;

END;

/ / DELIMITER;